DROP TABLE @PREFIX@mrconsoStaging IF EXISTS;
CREATE TABLE @PREFIX@mrconsoStaging
(CUI VARCHAR(8),
LAT VARCHAR(3),
TS VARCHAR(1),
LUI VARCHAR(9),
STT VARCHAR(3),
SUI VARCHAR(10),
ISPREF VARCHAR(1),
AUI VARCHAR(10),
SAUI VARCHAR(100),
SCUI VARCHAR(100),
SDUI VARCHAR(100),
SAB VARCHAR(40),
TTY VARCHAR(20),
CODE VARCHAR(100),
STR VARCHAR(3000),
SRL VARCHAR(20),
SUPPRESS VARCHAR(1),
CVF VARCHAR(50));
CREATE INDEX Index_1 ON @PREFIX@mrconsoStaging (CUI,AUI);
CREATE INDEX Index_2 ON @PREFIX@mrconsoStaging (CODE);
CREATE INDEX Index_3 ON @PREFIX@mrconsoStaging (SAB,CODE);
CREATE INDEX Index_4 ON @PREFIX@mrconsoStaging (AUI);
