--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.5.850
--   Created On : Thursday, 22 April, 2010 
--   DBMS       : Oracle 
--   -------------------------------------------------- 




--  Create Tables 
CREATE TABLE @PREFIX@associationPredicate
(
	associationPredicateGuid  VARCHAR2(36) NOT NULL,    --  Global unique identifier for a given associationPredicate. 
	relationGuid              VARCHAR2(36) NOT NULL,    --  Foreign key to the corresponding relation container. 
	associationName           VARCHAR2(100)    --  The local identifier of the relation itself.  associationName must match a local id of a supportedAssociationName in the corresponding mappings section. 
)
;

COMMENT ON TABLE @PREFIX@associationPredicate IS 'The local identifier of the relation itself.  associationName must match a local id of a supportedAssociationName in the corresponding mappings section.'
;
COMMENT ON COLUMN @PREFIX@associationPredicate.associationPredicateGuid  IS 'Global unique identifier for a given associationPredicate.'
;
COMMENT ON COLUMN @PREFIX@associationPredicate.relationGuid              IS 'Foreign key to the corresponding relation container.'
;
COMMENT ON COLUMN @PREFIX@associationPredicate.associationName           IS 'The local identifier of the relation itself.  associationName must match a local id of a supportedAssociationName in the corresponding mappings section.'
;

CREATE TABLE @PREFIX@codingScheme
(
	codingSchemeGuid   VARCHAR2(36) NOT NULL,    --  Global unique identifier for codingScheme entries. 
	codingSchemeName   VARCHAR2(50) NOT NULL,    --  The local identifier used to uniquely reference a coding scheme within the context of a message or container. codingSchemeName must match a local id of a supportedCodingScheme in the mappings table. 
	codingSchemeURI    VARCHAR2(250) NOT NULL,    --  The official URI for a coding scheme. This URI must also be present in the supportedCodingScheme entry that matches the codingSchemeName. 
	representsVersion  VARCHAR2(50),    --  The specific version of the resource represented by this coding scheme. 
	formalName         VARCHAR2(250),    --  The official or common name by which a coding scheme is known. (optional) 
	defaultLanguage    VARCHAR2(32),    --  The local identifier of the language that is used in all presentations, descriptions, etc. in this coding scheme if not otherwise specified. defaultLanguage must match a local id of a supportedLanguage in the mappings table. 
	approxNumConcepts  NUMBER(18),    --  The approximate number of entries in the lexical portion of this scheme. This is used as a hint for browsers and services. (optional) 
	description        CLOB,    --  Description of the content of the coding scheme. 
	copyright          CLOB,    --  Information about rights held in and over the resource. Typically, copyright information includes a statement about various property rights associated with the resource, including intellectual property rights. (optional) 
	isActive           CHAR(1) DEFAULT 1,    --  Boolean value to indicate the given coding scheme is active or not. 
	owner              VARCHAR2(250),    --  The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent. 
	status             VARCHAR2(50),    --  The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above. 
	effectiveDate      TIMESTAMP,    --  The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate.  If omitted, all temporal contexts are considered to be valid. 
	expirationDate     TIMESTAMP,    --  The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid. 
	releaseGuid        VARCHAR2(36),    --  Guid of the system release in which the given coding scheme is loaded. This field is a nullable field as a coding scheme can be loaded alone, with out a system release. 
	entryStateGuid     VARCHAR2(36)    --  Holds the reference to the entry state details of the coding scheme. 
)
;

COMMENT ON TABLE @PREFIX@codingScheme IS 'Table holds codingScheme identifiers and metadata. A resource that makes assertions about a collection of terminological entities.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.codingSchemeGuid   IS 'Global unique identifier for codingScheme entries.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.codingSchemeName   IS 'The local identifier used to uniquely reference a coding scheme within the context of a message or container. codingSchemeName must match a local id of a supportedCodingScheme in the mappings table.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.codingSchemeURI    IS 'The official URI for a coding scheme. This URI must also be present in the supportedCodingScheme entry that matches the codingSchemeName.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.representsVersion  IS 'The specific version of the resource represented by this coding scheme.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.formalName         IS 'The official or common name by which a coding scheme is known. (optional)'
;
COMMENT ON COLUMN @PREFIX@codingScheme.defaultLanguage    IS 'The local identifier of the language that is used in all presentations, descriptions, etc. in this coding scheme if not otherwise specified. defaultLanguage must match a local id of a supportedLanguage in the mappings table.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.approxNumConcepts  IS 'The approximate number of entries in the lexical portion of this scheme. This is used as a hint for browsers and services. (optional)'
;
COMMENT ON COLUMN @PREFIX@codingScheme.description        IS 'Description of the content of the coding scheme.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.copyright          IS 'Information about rights held in and over the resource. Typically, copyright information includes a statement about various property rights associated with the resource, including intellectual property rights. (optional)'
;
COMMENT ON COLUMN @PREFIX@codingScheme.isActive           IS 'Boolean value to indicate the given coding scheme is active or not.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.owner              IS 'The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.status             IS 'The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.effectiveDate      IS 'The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.expirationDate     IS 'The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.releaseGuid        IS 'Guid of the system release in which the given coding scheme is loaded. This field is a nullable field as a coding scheme can be loaded alone, with out a system release.'
;
COMMENT ON COLUMN @PREFIX@codingScheme.entryStateGuid     IS 'Holds the reference to the entry state details of the coding scheme.'
;

CREATE TABLE @PREFIX@csMultiAttrib
(
	csMultiAttribGuid  VARCHAR2(36) NOT NULL,    --  Global unique identifiers for codingScheme multi attribute entries. 
	codingSchemeGuid   VARCHAR2(36) NOT NULL,    --  Foreign key to the corresponding codingScheme. 
	attributeType      VARCHAR2(30) NOT NULL,    --  Type of the multi attribute stored. Typically "localName" or "source". 
	attributeValue     VARCHAR2(250) NOT NULL,    --  Value of the multi attributes. 
	subRef             VARCHAR2(250),    --  The page, subheading, id or other localized information within the source. Used to make a source reference more precise.  
	role               VARCHAR2(250),    --  The role or purpose of the source for this particular resource (e.g. author, distributor). 
	entryStateGuid     VARCHAR2(36)    --  Holds the reference to the entry state details. 
)
;

COMMENT ON TABLE @PREFIX@csMultiAttrib IS 'Table holds the localName and source for a given codingScheme.'
;
COMMENT ON COLUMN @PREFIX@csMultiAttrib.csMultiAttribGuid  IS 'Global unique identifiers for codingScheme multi attribute entries.'
;
COMMENT ON COLUMN @PREFIX@csMultiAttrib.codingSchemeGuid   IS 'Foreign key to the corresponding codingScheme.'
;
COMMENT ON COLUMN @PREFIX@csMultiAttrib.attributeType      IS 'Type of the multi attribute stored. Typically "localName" or "source".'
;
COMMENT ON COLUMN @PREFIX@csMultiAttrib.attributeValue     IS 'Value of the multi attributes.'
;
COMMENT ON COLUMN @PREFIX@csMultiAttrib.subRef             IS 'The page, subheading, id or other localized information within the source. Used to make a source reference more precise. '
;
COMMENT ON COLUMN @PREFIX@csMultiAttrib.role               IS 'The role or purpose of the source for this particular resource (e.g. author, distributor).'
;
COMMENT ON COLUMN @PREFIX@csMultiAttrib.entryStateGuid     IS 'Holds the reference to the entry state details.'
;

CREATE TABLE @PREFIX@csSupportedAttrib
(
	csSuppAttribGuid        VARCHAR2(36) NOT NULL,  
	codingSchemeGuid        VARCHAR2(36) NOT NULL,   
	supportedAttributeTag   VARCHAR2(30) NOT NULL,  
	id                      VARCHAR2(250) NOT NULL,    
	uri                     VARCHAR2(250),    
	idValue                 VARCHAR2(250),  
	associationNames        VARCHAR(250),   
	rootCode                VARCHAR2(250),   
	isForwardNavigable      CHAR(1),  
	isImported              CHAR(1),  
	equivalentCodingScheme  VARCHAR2(250),
	assemblyRule            VARCHAR2(250),  
	assnCodingScheme        VARCHAR(250),  
	assnNamespace           VARCHAR(250), 
	assnEntityCode          VARCHAR(200),  
	propertyType            VARCHAR(50)   
)
;

CREATE TABLE @PREFIX@entity
(
	entityGuid           VARCHAR2(36) NOT NULL,    --  Global unique identifier for the entities. 
	codingSchemeGuid     VARCHAR2(36) NOT NULL,    --  Foreign key to the corresponding codingScheme. 
	entityCode           VARCHAR2(200) NOT NULL,    --  unique entity code within coding system 
	entityCodeNamespace  VARCHAR2(50) NOT NULL,    --  Local identifier of the namespace of the entityCode. entityCodeNamespace must match a local id of a supportedNamespace in the corresponding mapping section.  If omitted, the URI of the defaultCodingScheme will be used as the namespace for the entity code. 
	isDefined            CHAR(1),    --  True means that this entityCode is considered to be completely defined (i.e. necessary and sufficient) within the context of the containing code system. False means that only the necessary components are present.  If omitted, the state of the entityCode definition is not known. 
	isAnonymous          CHAR(1),    --  True means that the entityCode is synthetic, and doesn't actually exist in the namespace.  isAnonymous is used for synthetic top and bottom nodes as well as blank or anonymous inner class definitions.  Default: False 
	description          CLOB,    --  Description of the entity. 
	isActive             CHAR(1) DEFAULT 1,    --  Boolean value to indicate the given entity is active or not. 
	owner                VARCHAR2(250),    --  The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent. 
	status               VARCHAR2(50),    --  The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above. 
	effectiveDate        TIMESTAMP,    --  The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate.  If omitted, all temporal contexts are considered to be valid. 
	expirationDate       TIMESTAMP,    --  The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid. 
	entryStateGuid       VARCHAR2(36),    --  Holds the reference to the entry state details of the given entity. 
	forwardName          VARCHAR(250),    --  Forward name of a defined association. 
	reverseName          VARCHAR(250),    --  Reverse name of a defined association. 
	isTransitive         CHAR(1),
	isNavigable          CHAR(1)
)
;

COMMENT ON TABLE @PREFIX@entity IS 'Table holds the entity related information. A set of lexical assertions about the intended meaning of a particular entity code.'
;
COMMENT ON COLUMN @PREFIX@entity.entityGuid           IS 'Global unique identifier for the entities.'
;
COMMENT ON COLUMN @PREFIX@entity.codingSchemeGuid     IS 'Foreign key to the corresponding codingScheme.'
;
COMMENT ON COLUMN @PREFIX@entity.entityCode           IS 'unique entity code within coding system'
;
COMMENT ON COLUMN @PREFIX@entity.entityCodeNamespace  IS 'Local identifier of the namespace of the entityCode. entityCodeNamespace must match a local id of a supportedNamespace in the corresponding mapping section.  If omitted, the URI of the defaultCodingScheme will be used as the namespace for the entity code.'
;
COMMENT ON COLUMN @PREFIX@entity.isDefined            IS 'True means that this entityCode is considered to be completely defined (i.e. necessary and sufficient) within the context of the containing code system. False means that only the necessary components are present.  If omitted, the state of the entityCode definition is not known.'
;
COMMENT ON COLUMN @PREFIX@entity.isAnonymous          IS 'True means that the entityCode is synthetic, and doesn''t actually exist in the namespace.  isAnonymous is used for synthetic top and bottom nodes as well as blank or anonymous inner class definitions.  Default: False'
;
COMMENT ON COLUMN @PREFIX@entity.description          IS 'Description of the entity.'
;
COMMENT ON COLUMN @PREFIX@entity.isActive             IS 'Boolean value to indicate the given entity is active or not.'
;
COMMENT ON COLUMN @PREFIX@entity.owner                IS 'The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent.'
;
COMMENT ON COLUMN @PREFIX@entity.status               IS 'The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above.'
;
COMMENT ON COLUMN @PREFIX@entity.effectiveDate        IS 'The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@entity.expirationDate       IS 'The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@entity.entryStateGuid       IS 'Holds the reference to the entry state details of the given entity.'
;
COMMENT ON COLUMN @PREFIX@entity.forwardName          IS 'Forward name of a defined association.'
;
COMMENT ON COLUMN @PREFIX@entity.reverseName          IS 'Reverse name of a defined association.'
;

CREATE TABLE @PREFIX@entityAssnQuals
(
	entityAssnQualsGuid  VARCHAR2(36) NOT NULL,    --  Global unique identifier for the association qualifier. 
	referenceGuid        VARCHAR2(36) NOT NULL,    --  Global unique identifier of  the triple to which the qualifier belongs to.. 
	qualifierName        VARCHAR2(50) NOT NULL,    --  The local name of a qualifier. Must be in supportedAssociationQualifier. 
	qualifierValue       VARCHAR2(250) NOT NULL,    --  The value associated with this qualifier, if any. 
	entryStateGuid       VARCHAR2(36)
)
;

COMMENT ON TABLE @PREFIX@entityAssnQuals IS 'Table holds the association instance qualifiers.'
;
COMMENT ON COLUMN @PREFIX@entityAssnQuals.entityAssnQualsGuid  IS 'Global unique identifier for the association qualifier.'
;
COMMENT ON COLUMN @PREFIX@entityAssnQuals.referenceGuid        IS 'Global unique identifier of  the triple to which the qualifier belongs to..'
;
COMMENT ON COLUMN @PREFIX@entityAssnQuals.qualifierName        IS 'The local name of a qualifier. Must be in supportedAssociationQualifier.'
;
COMMENT ON COLUMN @PREFIX@entityAssnQuals.qualifierValue       IS 'The value associated with this qualifier, if any.'
;

CREATE TABLE @PREFIX@entityAssnsToData
(
	entityAssnsDataGuid        VARCHAR2(36) NOT NULL,    --  Global unique identifier for the association instance. 
	associationPredicateGuid   VARCHAR2(36) NOT NULL,    --  Foreign key to the corresponding associationPredicate. 
	sourceEntityCode           VARCHAR2(200) NOT NULL,    --  The entity code of the source entity. 
	sourceEntityCodeNamespace  VARCHAR2(50) NOT NULL,    --  Local name of the namespace of the sourceEntityCode. sourceEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of sourceEntityCode namespace is the codingSchemeURI of the containing coding scheme. 
	associationInstanceId      VARCHAR2(50),    --  Identifier that uniqely names this entry within the context of the associationInstance. 
	isDefining                 CHAR(1),    --  True means that this association instance is considered to be part of the definition of source entity, false means that it is an "accidental" characteristic. If omitted (null), this information is not known. 
	isInferred                 CHAR(1),    --  True means that this association instance isn't asserted in the scheme, but is inferred by a classifier.  Default: false 
	dataValue                  CLOB,    --  associated data value 
	isActive                   CHAR(1),    --  Boolean value to indicate the given instance is active or not. 
	owner                      VARCHAR2(250),    --  The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent. 
	status                     VARCHAR2(50),    --  The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above. 
	effectiveDate              TIMESTAMP,    --  The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate. If omitted, all temporal contexts are considered to be valid. 
	expirationDate             TIMESTAMP,    --  The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid. 
	entryStateGuid             VARCHAR2(36)    --  Holds the reference to the entry state details of the given triple. 
)
;

COMMENT ON TABLE @PREFIX@entityAssnsToData IS 'Place holder for the instance of an association, source being an entity and target being data.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.entityAssnsDataGuid        IS 'Global unique identifier for the association instance.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.associationPredicateGuid   IS 'Foreign key to the corresponding associationPredicate.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.sourceEntityCode           IS 'The entity code of the source entity.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.sourceEntityCodeNamespace  IS 'Local name of the namespace of the sourceEntityCode. sourceEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of sourceEntityCode namespace is the codingSchemeURI of the containing coding scheme.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.associationInstanceId      IS 'Identifier that uniqely names this entry within the context of the associationInstance.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.isDefining                 IS 'True means that this association instance is considered to be part of the definition of source entity, false means that it is an "accidental" characteristic. If omitted (null), this information is not known.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.isInferred                 IS 'True means that this association instance isn''t asserted in the scheme, but is inferred by a classifier.  Default: false'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.dataValue                  IS 'associated data value'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.isActive                   IS 'Boolean value to indicate the given instance is active or not.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.owner                      IS 'The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.status                     IS 'The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.effectiveDate              IS 'The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate. If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.expirationDate             IS 'The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToData.entryStateGuid             IS 'Holds the reference to the entry state details of the given triple.'
;

CREATE TABLE @PREFIX@entityAssnsToEntity
(
	entityAssnsGuid            VARCHAR2(36) NOT NULL,    --  Global unique identifier for the association instance. 
	associationPredicateGuid   VARCHAR2(36) NOT NULL,    --  Foreign key to the corresponding associationPredicate. 
	sourceEntityCode           VARCHAR2(200) NOT NULL,    --  The entity code of the source entity. 
	sourceEntityCodeNamespace  VARCHAR2(50) NOT NULL,    --  Local name of the namespace of the sourceEntityCode. sourceEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of sourceEntityCode namespace is the codingSchemeURI of the containing coding scheme. 
	targetEntityCode           VARCHAR2(200) NOT NULL,    --  The entity code of the target entity. 
	targetEntityCodeNamespace  VARCHAR2(50) NOT NULL,    --  Local name of the namespace of the targetEntityCode. targetEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of targetEntityCode namespace is the codingSchemeURI of the containing coding scheme. 
	associationInstanceId      VARCHAR2(50),    --  The unique identifier assigned to the particular relation, from, to triple. 
	isDefining                 CHAR(1),    --  True means that this association instance is considered to be part of the definition of source entity, false means that it is an "accidental" characteristic. If omitted, this information is not known. 
	isInferred                 CHAR(1),    --  True means that this association instance isn't asserted in the scheme, but is inferred by a classifier.  Default: false 
	isActive                   CHAR(1),    --  Boolean value to indicate the given instance is active or not. 
	owner                      VARCHAR2(250),    --  The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent. 
	status                     VARCHAR2(50),    --  The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above. 
	effectiveDate              TIMESTAMP,    --  The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate. If omitted, all temporal contexts are considered to be valid. 
	expirationDate             TIMESTAMP,    --  The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid. 
	entryStateGuid             VARCHAR2(36)    --  Holds the reference to the entry state details of the given triple. 
)
;

COMMENT ON TABLE @PREFIX@entityAssnsToEntity IS 'Place holder for the instance of an association, both source and target being entities. '
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.entityAssnsGuid            IS 'Global unique identifier for the association instance.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.associationPredicateGuid   IS 'Foreign key to the corresponding associationPredicate.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.sourceEntityCode           IS 'The entity code of the source entity.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.sourceEntityCodeNamespace  IS 'Local name of the namespace of the sourceEntityCode. sourceEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of sourceEntityCode namespace is the codingSchemeURI of the containing coding scheme.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.targetEntityCode           IS 'The entity code of the target entity.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.targetEntityCodeNamespace  IS 'Local name of the namespace of the targetEntityCode. targetEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of targetEntityCode namespace is the codingSchemeURI of the containing coding scheme.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.associationInstanceId      IS 'The unique identifier assigned to the particular relation, from, to triple.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.isDefining                 IS 'True means that this association instance is considered to be part of the definition of source entity, false means that it is an "accidental" characteristic. If omitted, this information is not known.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.isInferred                 IS 'True means that this association instance isn''t asserted in the scheme, but is inferred by a classifier.  Default: false'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.isActive                   IS 'Boolean value to indicate the given instance is active or not.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.owner                      IS 'The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.status                     IS 'The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.effectiveDate              IS 'The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate. If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.expirationDate             IS 'The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntity.entryStateGuid             IS 'Holds the reference to the entry state details of the given triple.'
;

CREATE TABLE @PREFIX@entityAssnsToEntityTr
(
	entityAssnsTrGuid          VARCHAR2(36) NOT NULL,    --  Global unique identifier for the transitive relation. 
	associationPredicateGuid   VARCHAR2(36) NOT NULL,    --  Foreign key to the corresponding association. 
	sourceEntityCode           VARCHAR2(200) NOT NULL,    --  The entity code of the source entity. 
	sourceEntityCodeNamespace  VARCHAR2(50) NOT NULL,    --  Local name of the namespace of the sourceEntityCode. sourceEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of sourceEntityCode namespace is the codingSchemeURI of the containing coding scheme. 
	targetEntityCode           VARCHAR2(200) NOT NULL,    --  The entity code of the target entity. 
	targetEntityCodeNamespace  VARCHAR2(50) NOT NULL    --  Local name of the namespace of the targetEntityCode. targetEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of targetEntityCode namespace is the codingSchemeURI of the containing coding scheme. 
)
;

COMMENT ON TABLE @PREFIX@entityAssnsToEntityTr IS 'Table holds the transitive relation details associated with the triple.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntityTr.entityAssnsTrGuid          IS 'Global unique identifier for the transitive relation.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntityTr.associationPredicateGuid   IS 'Foreign key to the corresponding association.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntityTr.sourceEntityCode           IS 'The entity code of the source entity.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntityTr.sourceEntityCodeNamespace  IS 'Local name of the namespace of the sourceEntityCode. sourceEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of sourceEntityCode namespace is the codingSchemeURI of the containing coding scheme.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntityTr.targetEntityCode           IS 'The entity code of the target entity.'
;
COMMENT ON COLUMN @PREFIX@entityAssnsToEntityTr.targetEntityCodeNamespace  IS 'Local name of the namespace of the targetEntityCode. targetEntityCodeNamespace must match a local id of a supportedNamespace in the corresponding mappings section.  If omitted, the URI of targetEntityCode namespace is the codingSchemeURI of the containing coding scheme.'
;

CREATE TABLE @PREFIX@entityType
(
	entityGuid  VARCHAR2(36) NOT NULL,    --  Foreign Key to the guid of entity table. 
	entityType  VARCHAR2(50) NOT NULL    --  Type of entity. 
)
;

COMMENT ON TABLE @PREFIX@entityType IS 'Table defines the type of the entity being loaded into entity table. Primarily concept, instance and association. But the entity types are not restricted just to these three types.'
;
COMMENT ON COLUMN @PREFIX@entityType.entityGuid  IS 'Foreign Key to the guid of entity table.'
;
COMMENT ON COLUMN @PREFIX@entityType.entityType  IS 'Type of entity.'
;

CREATE TABLE @PREFIX@entryState
(
	entryStateGuid      VARCHAR2(36) NOT NULL,    --  Global unique identifier for the entry state. 
	entryGuid           VARCHAR2(36) NOT NULL,    --  The Global unique identifier of the object being revised.  
	entryType           VARCHAR2(50) NOT NULL,    --  Type of the version able object being revised. 
	changeType          VARCHAR2(15) NOT NULL,    --  The type of change that occurred between this state and the previous. 
	relativeOrder       NUMBER(18) NOT NULL,    --  The relative order that this state change should be applied within the context of the containing revision. 
	revisionGuid        VARCHAR2(36),    --  Global unique identifier of the revision in which the version able object is being revised. 
	prevRevisionGuid    VARCHAR2(36),    --  Global unique identifier of the revision in which the version able object was previously revised. 
	prevEntryStateGuid  VARCHAR2(36)    --  Global unique identifier of the previous entry state for the given version able object. 
)
;

COMMENT ON TABLE @PREFIX@entryState IS 'Table holds the entryState details of the codingScheme(s). Represents a change that occurred between the current state of the versionable entry and an immediately preceeding state of the same entry.'
;
COMMENT ON COLUMN @PREFIX@entryState.entryStateGuid      IS 'Global unique identifier for the entry state.'
;
COMMENT ON COLUMN @PREFIX@entryState.entryGuid           IS 'The Global unique identifier of the object being revised. '
;
COMMENT ON COLUMN @PREFIX@entryState.entryType           IS 'Type of the version able object being revised.'
;
COMMENT ON COLUMN @PREFIX@entryState.changeType          IS 'The type of change that occurred between this state and the previous.'
;
COMMENT ON COLUMN @PREFIX@entryState.relativeOrder       IS 'The relative order that this state change should be applied within the context of the containing revision.'
;
COMMENT ON COLUMN @PREFIX@entryState.revisionGuid        IS 'Global unique identifier of the revision in which the version able object is being revised.'
;
COMMENT ON COLUMN @PREFIX@entryState.prevRevisionGuid    IS 'Global unique identifier of the revision in which the version able object was previously revised.'
;
COMMENT ON COLUMN @PREFIX@entryState.prevEntryStateGuid  IS 'Global unique identifier of the previous entry state for the given version able object.'
;

CREATE TABLE @PREFIX@property
(
	propertyGuid          VARCHAR2(36) NOT NULL,    --  Global unique identifier for a given property. 
	referenceGuid         VARCHAR2(36) NOT NULL,    --  Guid of the model object to which a given property belongs to. 
	referenceType         VARCHAR2(50) NOT NULL,    --  Type of the model object to which a given property belongs to. Ex: entity, codingScheme etc. 
	propertyId            VARCHAR2(50),    --  The unique name of the property within the context of the coded entry 
	propertyType          VARCHAR2(15),    --  The LexGrid model element that a given property represents.  As an example, the codingScheme "copyright" attribute could be represented by a property with a propertyType that mapped to lgCS:copyRight. Must match a local id of a supportedPropertyType in the corresponding mappings section. 
	propertyName          VARCHAR2(250) NOT NULL,    --  The local identifier that defines the meaning of this particular property entry. Must match a local id of a supportedProperty in the corresponding mapping section. 
	language              VARCHAR2(32),    --  The local identifier of the language of the property value. Must match a local id of a supportedLanguage in the corresponding mappings section. If omitted, and language is applicable to this property, the defaultLanguage of the surrounding resource is used. 
	format                VARCHAR2(50),    --  Data type format of the property value. 
	isPreferred           CHAR(1),    --  True means that, if the text meets the selection criteria, it should be the preferred form. For a given language there should be only one preferred presentation. 
	matchIfNoContext      CHAR(1),    --  True means that this presentation is valid in a acontextual setting - that it is always valid in the given language.  Default: true  if there are no property usageContexts, false otherwise. 
	degreeOfFidelity      VARCHAR2(50),    --  A local identifier that states how closely a term approximates the intended meaning of an entry code. degreeOfFidelity must match a local id of a supportedDegreeOfFidelity in the corresponding mappings section. 
	representationalForm  VARCHAR2(50),    --  A local identifier that states how the term represents the concept (abbrev, acronym, etc.) representationalForm must match a local id of a representationalForm in the corresponding mappings section. 
	propertyValue         CLOB NOT NULL,    --  The value of the property associated with this particular resource.  Note that "text" may be any type, including a URI, html fragment, etc. 
	isActive              CHAR(1) DEFAULT 1,    --  Boolean value to indicate the given property is active or not. 
	owner                 VARCHAR2(250),    --  The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent. 
	status                VARCHAR2(50),    --  The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above. 
	effectiveDate         TIMESTAMP,    --  The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate.  If omitted, all temporal contexts are considered to be valid. 
	expirationDate        TIMESTAMP,    --  The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid. 
	entryStateGuid        VARCHAR2(36)    --  Holds the reference to the entry state details of the given property. 
)
;

COMMENT ON TABLE @PREFIX@property IS 'Table holds the property information related to codingScheme, entity and other model objects. A description, definition, annotation or other attribute that serves to further define or identify a resource.'
;
COMMENT ON COLUMN @PREFIX@property.propertyGuid          IS 'Global unique identifier for a given property.'
;
COMMENT ON COLUMN @PREFIX@property.referenceGuid         IS 'Guid of the model object to which a given property belongs to.'
;
COMMENT ON COLUMN @PREFIX@property.referenceType         IS 'Type of the model object to which a given property belongs to. Ex: entity, codingScheme etc.'
;
COMMENT ON COLUMN @PREFIX@property.propertyId            IS 'The unique name of the property within the context of the coded entry'
;
COMMENT ON COLUMN @PREFIX@property.propertyType          IS 'The LexGrid model element that a given property represents.  As an example, the codingScheme "copyright" attribute could be represented by a property with a propertyType that mapped to lgCS:copyRight. Must match a local id of a supportedPropertyType in the corresponding mappings section.'
;
COMMENT ON COLUMN @PREFIX@property.propertyName          IS 'The local identifier that defines the meaning of this particular property entry. Must match a local id of a supportedProperty in the corresponding mapping section.'
;
COMMENT ON COLUMN @PREFIX@property.language              IS 'The local identifier of the language of the property value. Must match a local id of a supportedLanguage in the corresponding mappings section. If omitted, and language is applicable to this property, the defaultLanguage of the surrounding resource is used.'
;
COMMENT ON COLUMN @PREFIX@property.format                IS 'Data type format of the property value.'
;
COMMENT ON COLUMN @PREFIX@property.isPreferred           IS 'True means that, if the text meets the selection criteria, it should be the preferred form. For a given language there should be only one preferred presentation.'
;
COMMENT ON COLUMN @PREFIX@property.matchIfNoContext      IS 'True means that this presentation is valid in a acontextual setting - that it is always valid in the given language.  Default: true  if there are no property usageContexts, false otherwise.'
;
COMMENT ON COLUMN @PREFIX@property.degreeOfFidelity      IS 'A local identifier that states how closely a term approximates the intended meaning of an entry code. degreeOfFidelity must match a local id of a supportedDegreeOfFidelity in the corresponding mappings section.'
;
COMMENT ON COLUMN @PREFIX@property.representationalForm  IS 'A local identifier that states how the term represents the concept (abbrev, acronym, etc.) representationalForm must match a local id of a representationalForm in the corresponding mappings section.'
;
COMMENT ON COLUMN @PREFIX@property.propertyValue         IS 'The value of the property associated with this particular resource.  Note that "text" may be any type, including a URI, html fragment, etc.'
;
COMMENT ON COLUMN @PREFIX@property.isActive              IS 'Boolean value to indicate the given property is active or not.'
;
COMMENT ON COLUMN @PREFIX@property.owner                 IS 'The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent.'
;
COMMENT ON COLUMN @PREFIX@property.status                IS 'The status code associated with the particular resource. The semantics and business rules of entryStatus are defined by the containing system, but there needs to be a mapping into isActive above.'
;
COMMENT ON COLUMN @PREFIX@property.effectiveDate         IS 'The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@property.expirationDate        IS 'The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@property.entryStateGuid        IS 'Holds the reference to the entry state details of the given property.'
;

CREATE TABLE @PREFIX@propertyLinks
(
	propertyLinksGuid   VARCHAR2(36) NOT NULL,    --  Global unique identifier for a given property link. 
	sourcePropertyGuid  VARCHAR2(36) NOT NULL,    --  Foreign key to the source property guid. (The identifier of the first property in the link.) 
	link                VARCHAR2(250) NOT NULL,    --  The local name of the type of link between properties.  (Examples include acronymFor, abbreviationOf, spellingVariantOf, etc. Must be in supportedPropertyLink) propertyLink must match a local id of a supportedPropertyLink in the corresponding mapping section. 
	targetPropertyGuid  VARCHAR2(36) NOT NULL    --  Foreign key to the target property guid. (The identifier of the second property in the link.) 
)
;

COMMENT ON TABLE @PREFIX@propertyLinks IS 'Table holds the link between two properties.'
;
COMMENT ON COLUMN @PREFIX@propertyLinks.propertyLinksGuid   IS 'Global unique identifier for a given property link.'
;
COMMENT ON COLUMN @PREFIX@propertyLinks.sourcePropertyGuid  IS 'Foreign key to the source property guid. (The identifier of the first property in the link.)'
;
COMMENT ON COLUMN @PREFIX@propertyLinks.link                IS 'The local name of the type of link between properties.  (Examples include acronymFor, abbreviationOf, spellingVariantOf, etc. Must be in supportedPropertyLink) propertyLink must match a local id of a supportedPropertyLink in the corresponding mapping section.'
;
COMMENT ON COLUMN @PREFIX@propertyLinks.targetPropertyGuid  IS 'Foreign key to the target property guid. (The identifier of the second property in the link.)'
;

CREATE TABLE @PREFIX@propertyMultiAttrib
(
	propMultiAttribGuid  VARCHAR2(36) NOT NULL,    --  Global unique identifier for multi attributes entries. 
	propertyGuid         VARCHAR2(36) NOT NULL,    --  Foreign key to the corresponding property. 
	attributeType        VARCHAR2(30) NOT NULL,    --  Type of the multi attribute stored. Typically "qualifier" or "source" or "usage context". 
	attributeId          VARCHAR2(50),    --  Name of the property qualifier. In case of source and usage context value will be null. 
	attributeValue       VARCHAR2(250),    --  Value of the multi attributes. 
	subRef               VARCHAR2(250),    --  The page, subheading, id or other localized information within the source. Used to make a source reference more precise.  
	role                 VARCHAR2(250),    --  The role or purpose of the source for this particular resource (e.g. author, distributor).
	qualifierType 		 VARCHAR2(250),	   --  The qualifier type of a property.	 
	entryStateGuid       VARCHAR2(36)    --  Holds the reference to the entry state. 
)
;

COMMENT ON TABLE @PREFIX@propertyMultiAttrib IS 'Table holds the property mulit attributes like qualifiers, sources and usage contexts of a given property.'
;
COMMENT ON COLUMN @PREFIX@propertyMultiAttrib.propMultiAttribGuid  IS 'Global unique identifier for multi attributes entries.'
;
COMMENT ON COLUMN @PREFIX@propertyMultiAttrib.propertyGuid         IS 'Foreign key to the corresponding property.'
;
COMMENT ON COLUMN @PREFIX@propertyMultiAttrib.attributeType        IS 'Type of the multi attribute stored. Typically "qualifier" or "source" or "usage context".'
;
COMMENT ON COLUMN @PREFIX@propertyMultiAttrib.attributeId          IS 'Name of the property qualifier. In case of source and usage context value will be null.'
;
COMMENT ON COLUMN @PREFIX@propertyMultiAttrib.attributeValue       IS 'Value of the multi attributes.'
;
COMMENT ON COLUMN @PREFIX@propertyMultiAttrib.subRef               IS 'The page, subheading, id or other localized information within the source. Used to make a source reference more precise. '
;
COMMENT ON COLUMN @PREFIX@propertyMultiAttrib.role                 IS 'The role or purpose of the source for this particular resource (e.g. author, distributor).'
;
COMMENT ON COLUMN @PREFIX@propertyMultiAttrib.entryStateGuid       IS 'Holds the reference to the entry state.'
;

CREATE TABLE @PREFIX@relation
(
	relationGuid               VARCHAR2(36) NOT NULL,    --  Global unique identifier for a given relation. 
	codingSchemeGuid           VARCHAR2(36) NOT NULL,    --  Foreign key to the corresponding coding scheme. 
	containerName              VARCHAR2(50) NOT NULL,    --  The unique identifier of a collection of associations. Required if there is one or more collection of relations in a coding scheme. Must be in supportedContainerName. 
	isMapping                  CHAR(1),    --  An indicator that a set of associations represents a mapping between two terminologies if value is true. 
	representsVersion          VARCHAR2(50),
	sourceCodingScheme         VARCHAR2(50),    --  If not supplied in associationInstance, this is the default source codingScheme. 
	sourceCodingSchemeVersion  VARCHAR2(50),    --  If not supplied in associationInstance, this is the default source codingScheme version. 
	targetCodingScheme         VARCHAR2(50),    --  If not supplied in associationInstance, this is the default target codingScheme. 
	targetCodingSchemeVersion  VARCHAR2(50),    --  If not supplied in associationInstance, this is the default source codingScheme version. 
	description                CLOB,    --  Description of the relation container. 
	isActive                   CHAR(1),    --  Boolean value to indicate the given relation is active or not. 
	owner                      VARCHAR2(250),    --  The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent. 
	status                     VARCHAR2(50),    --  The status code associated with the particular resource. The semantics and business rules of entry Status are defined by the containing system, but there needs to be a mapping into isActive above. 
	effectiveDate              TIMESTAMP,    --  The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate.  If omitted, all temporal contexts are considered to be valid. 
	expirationDate             TIMESTAMP,    --  The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid. 
	entryStateGuid             VARCHAR2(36)    --  Holds the reference to the entry state details of the given relation. 
)
;

COMMENT ON TABLE @PREFIX@relation IS 'A collection of relations that represent a particular point of view or community.'
;
COMMENT ON COLUMN @PREFIX@relation.relationGuid               IS 'Global unique identifier for a given relation.'
;
COMMENT ON COLUMN @PREFIX@relation.codingSchemeGuid           IS 'Foreign key to the corresponding coding scheme.'
;
COMMENT ON COLUMN @PREFIX@relation.containerName              IS 'The unique identifier of a collection of associations. Required if there is one or more collection of relations in a coding scheme. Must be in supportedContainerName.'
;
COMMENT ON COLUMN @PREFIX@relation.isMapping                  IS 'An indicator that a set of associations represents a mapping between two terminologies if value is true.'
;
COMMENT ON COLUMN @PREFIX@relation.sourceCodingScheme         IS 'If not supplied in associationInstance, this is the default source codingScheme.'
;
COMMENT ON COLUMN @PREFIX@relation.sourceCodingSchemeVersion  IS 'If not supplied in associationInstance, this is the default source codingScheme version.'
;
COMMENT ON COLUMN @PREFIX@relation.targetCodingScheme         IS 'If not supplied in associationInstance, this is the default target codingScheme.'
;
COMMENT ON COLUMN @PREFIX@relation.targetCodingSchemeVersion  IS 'If not supplied in associationInstance, this is the default source codingScheme version.'
;
COMMENT ON COLUMN @PREFIX@relation.description                IS 'Description of the relation container.'
;
COMMENT ON COLUMN @PREFIX@relation.isActive                   IS 'Boolean value to indicate the given relation is active or not.'
;
COMMENT ON COLUMN @PREFIX@relation.owner                      IS 'The owner of the resource. The specific semantics of owner is defined by the busniess rules of the implementor, including the rules of the owner field is absent.'
;
COMMENT ON COLUMN @PREFIX@relation.status                     IS 'The status code associated with the particular resource. The semantics and business rules of entry Status are defined by the containing system, but there needs to be a mapping into isActive above.'
;
COMMENT ON COLUMN @PREFIX@relation.effectiveDate              IS 'The date and time that this resource is considered to be active.  To be considered active, isActive must be true, and the temporal context of the operation must be greater than effectiveDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@relation.expirationDate             IS 'The date and time that this resource is considered to become inActive.  To be considered active, isActive must be true, and the temporal context of the operation must be less than expirationDate.  If omitted, all temporal contexts are considered to be valid.'
;
COMMENT ON COLUMN @PREFIX@relation.entryStateGuid             IS 'Holds the reference to the entry state details of the given relation.'
;

--  Create Primary Key Constraints 
ALTER TABLE @PREFIX@associationPredicate ADD CONSTRAINT PK_associationPredicate 
	PRIMARY KEY (associationPredicateGuid)
;

ALTER TABLE @PREFIX@codingScheme ADD CONSTRAINT PK_codingScheme 
	PRIMARY KEY (codingSchemeGuid)
;

ALTER TABLE @PREFIX@csMultiAttrib ADD CONSTRAINT PK_csMultiAttribGuid 
	PRIMARY KEY (csMultiAttribGuid)
;

ALTER TABLE @PREFIX@csSupportedAttrib ADD CONSTRAINT PK_mappingGuid 
	PRIMARY KEY (csSuppAttribGuid)
;

ALTER TABLE @PREFIX@entity ADD CONSTRAINT PK_entity 
	PRIMARY KEY (entityGuid)
;

ALTER TABLE @PREFIX@entityAssnQuals ADD CONSTRAINT PK_entityAssnQuals 
	PRIMARY KEY (entityAssnQualsGuid)
;

ALTER TABLE @PREFIX@entityAssnsToData ADD CONSTRAINT PK_entityAssnsToData 
	PRIMARY KEY (entityAssnsDataGuid)
;

ALTER TABLE @PREFIX@entityAssnsToEntity ADD CONSTRAINT PK_entityAssnsToEntity 
	PRIMARY KEY (entityAssnsGuid)
;

ALTER TABLE @PREFIX@entityAssnsToEntityTr ADD CONSTRAINT PK_entityAssnsToEntityTr 
	PRIMARY KEY (entityAssnsTrGuid)
;

ALTER TABLE @PREFIX@entryState ADD CONSTRAINT PK_entryState 
	PRIMARY KEY (entryStateGuid)
;

ALTER TABLE @PREFIX@property ADD CONSTRAINT PK_property 
	PRIMARY KEY (propertyGuid)
;

ALTER TABLE @PREFIX@propertyLinks ADD CONSTRAINT PK_propertyLinksGuid 
	PRIMARY KEY (propertyLinksGuid)
;

ALTER TABLE @PREFIX@propertyMultiAttrib ADD CONSTRAINT PK_propMultiAttribGuid 
	PRIMARY KEY (propMultiAttribGuid)
;

ALTER TABLE @PREFIX@relation ADD CONSTRAINT PK_relation 
	PRIMARY KEY (relationGuid)
;

--  Create Indexes 
ALTER TABLE @PREFIX@associationPredicate
	ADD CONSTRAINT UQ_association UNIQUE (relationGuid, associationName)
;

CREATE INDEX idx_csURI ON @PREFIX@codingScheme
(codingSchemeURI ASC)
;

CREATE INDEX idx_csURIVersion ON @PREFIX@codingScheme
(codingSchemeURI ASC, representsVersion ASC)
;

CREATE INDEX idx_csName ON @PREFIX@codingScheme
(codingSchemeName ASC)
;

CREATE INDEX idx_csNameVersion ON @PREFIX@codingScheme
(codingSchemeName ASC, representsVersion ASC)
;

CREATE INDEX idx_csMultiAttrib ON @PREFIX@csMultiAttrib
(codingSchemeGuid ASC, attributeType ASC)
;

ALTER TABLE @PREFIX@csSupportedAttrib
	ADD CONSTRAINT UQ_mapping UNIQUE (codingSchemeGuid, supportedAttributeTag, id)
;

CREATE INDEX idx_entity ON @PREFIX@entity
(codingSchemeGuid ASC, entityCode ASC)
;

CREATE INDEX idx_entityNS ON @PREFIX@entity
(codingSchemeGuid ASC, entityCode ASC, entityCodeNamespace ASC)
;

ALTER TABLE @PREFIX@entityAssnQuals
	ADD CONSTRAINT UQ_entityAssnQuals UNIQUE (referenceGuid, qualifierName, qualifierValue)
;

ALTER TABLE @PREFIX@entityAssnsToData
	ADD CONSTRAINT UQ_entAsToData_source UNIQUE (sourceEntityCode, sourceEntityCodeNamespace)
;

CREATE INDEX idx_entAsToData_source ON @PREFIX@entityAssnsToData
(associationPredicateGuid ASC, sourceEntityCode ASC)
;

CREATE INDEX idx_entAsToEnt_source ON @PREFIX@entityAssnsToEntity
(associationPredicateGuid ASC, sourceEntityCode ASC)
;

CREATE INDEX idx_entAsToEnt_sourceNS ON @PREFIX@entityAssnsToEntity
(associationPredicateGuid ASC, sourceEntityCode ASC, sourceEntityCodeNamespace ASC)
;

CREATE INDEX idx_entAsToEnt_target ON @PREFIX@entityAssnsToEntity
(associationPredicateGuid ASC, targetEntityCode ASC)
;

CREATE INDEX idx_entAsToEnt_targetNS ON @PREFIX@entityAssnsToEntity
(associationPredicateGuid ASC, targetEntityCode ASC, targetEntityCodeNamespace ASC)
;

ALTER TABLE @PREFIX@entityAssnsToEntityTr
	ADD CONSTRAINT UQ_sourceTargetCombo UNIQUE (sourceEntityCode, sourceEntityCodeNamespace, targetEntityCode, targetEntityCodeNamespace)
;

CREATE INDEX idx_entAsToEntTr_source ON @PREFIX@entityAssnsToEntityTr
(associationPredicateGuid ASC, sourceEntityCode ASC, sourceEntityCodeNamespace ASC)
;

CREATE INDEX idx_entAsToEntTr_target ON @PREFIX@entityAssnsToEntityTr
(associationPredicateGuid ASC, targetEntityCode ASC, targetEntityCodeNamespace ASC)
;

ALTER TABLE @PREFIX@property
	ADD CONSTRAINT UQ_property UNIQUE (referenceGuid, propertyName, propertyId)
;

CREATE INDEX idx_referenceGuid ON @PREFIX@property
(referenceGuid ASC)
;

ALTER TABLE @PREFIX@propertyLinks
	ADD CONSTRAINT UQ_propLinks UNIQUE (sourcePropertyGuid, link, targetPropertyGuid)
;

CREATE INDEX idx_sourcePropertyGuid ON @PREFIX@propertyLinks
(sourcePropertyGuid ASC)
;

CREATE INDEX idx_targetPropertyGuid ON @PREFIX@propertyLinks
(targetPropertyGuid ASC)
;

CREATE INDEX idx_propertyMultiAttrib ON @PREFIX@propertyMultiAttrib
(propertyGuid ASC)
;

ALTER TABLE @PREFIX@propertyMultiAttrib
	ADD CONSTRAINT UQ_propertyMultiAttrib UNIQUE (propertyGuid, attributeType, attributeId)
;

ALTER TABLE @PREFIX@relation
	ADD CONSTRAINT UQ_relation_containerName UNIQUE (codingSchemeGuid,containerName)
;


--  Create Foreign Key Constraints 
ALTER TABLE @PREFIX@associationPredicate ADD CONSTRAINT FK_associationPredica_relation 
	FOREIGN KEY (relationGuid) REFERENCES @PREFIX@relation (relationGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@codingScheme ADD CONSTRAINT FK_cs_releaseGuid 
	FOREIGN KEY (releaseGuid) REFERENCES @PREFIX@systemRelease (releaseGuid)
;

ALTER TABLE @PREFIX@csMultiAttrib ADD CONSTRAINT FK_csMulti_csGuid 
	FOREIGN KEY (codingSchemeGuid) REFERENCES @PREFIX@codingScheme (codingSchemeGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@csSupportedAttrib ADD CONSTRAINT FK_map_csGuid 
	FOREIGN KEY (codingSchemeGuid) REFERENCES @PREFIX@codingScheme (codingSchemeGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@entity ADD CONSTRAINT FK_ent_csGuid 
	FOREIGN KEY (codingSchemeGuid) REFERENCES @PREFIX@codingScheme (codingSchemeGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@entityAssnsToData ADD CONSTRAINT FK_entAsToData_assnGuid 
	FOREIGN KEY (associationPredicateGuid) REFERENCES @PREFIX@associationPredicate (associationPredicateGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@entityAssnsToEntity ADD CONSTRAINT FK_entAsToEnt_assnGuid 
	FOREIGN KEY (associationPredicateGuid) REFERENCES @PREFIX@associationPredicate (associationPredicateGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@entityAssnsToEntityTr ADD CONSTRAINT FK_entAsToEntTr_assnGuid 
	FOREIGN KEY (associationPredicateGuid) REFERENCES @PREFIX@associationPredicate (associationPredicateGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@entityType ADD CONSTRAINT FK_eType_entityGuid 
	FOREIGN KEY (entityGuid) REFERENCES @PREFIX@entity (entityGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@entryState ADD CONSTRAINT FK_es_prevEntryStateGuid 
	FOREIGN KEY (prevEntryStateGuid) REFERENCES @PREFIX@entryState (entryStateGuid)
;

ALTER TABLE @PREFIX@entryState ADD CONSTRAINT FK_es_revisionGuid 
	FOREIGN KEY (revisionGuid) REFERENCES @PREFIX@revision (revisionGuid)
;

ALTER TABLE @PREFIX@entryState ADD CONSTRAINT FK_es_prevRevisionGuid 
	FOREIGN KEY (prevRevisionGuid) REFERENCES @PREFIX@revision (revisionGuid)
;

ALTER TABLE @PREFIX@propertyLinks ADD CONSTRAINT FK_pLinks_sPropGuid 
	FOREIGN KEY (sourcePropertyGuid) REFERENCES @PREFIX@property (propertyGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@propertyLinks ADD CONSTRAINT FK_pLinks_tPropGuid 
	FOREIGN KEY (targetPropertyGuid) REFERENCES @PREFIX@property (propertyGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@propertyMultiAttrib ADD CONSTRAINT FK_pma_propertyGuid 
	FOREIGN KEY (propertyGuid) REFERENCES @PREFIX@property (propertyGuid)
ON DELETE CASCADE
;

ALTER TABLE @PREFIX@relation ADD CONSTRAINT FK_relation_codingScheme 
	FOREIGN KEY (codingSchemeGuid) REFERENCES @PREFIX@codingScheme (codingSchemeGuid)
ON DELETE CASCADE
;
