--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.5.850
--   Created On : Friday, 28 May, 2010 
--   DBMS       : Oracle 
--   -------------------------------------------------- 




--  Create Tables 
CREATE TABLE @PREFIX@registry
(
	registryGuid         VARCHAR2(36) NOT NULL,    --  global unique identifier of the resource loaded. 
	resourceURI          VARCHAR2(250),    --  URI of the resource loaded into lexEVS system. 
	resourceVersion      VARCHAR2(50),    --  The external version identifier that this particular instance represents. 
	resourceType         VARCHAR2(50),    --  The type this registry entry represents. Ex. CodingScheme, ValueDomain, PickList, History etc. 
	dbURI                VARCHAR2(250),    --  URL of the resource that contains this image 
	dbName               VARCHAR2(50),    --  name of the database.  
	prefix               VARCHAR2(20),    --  Instance identifier (e.g. database prefix, HTML sub-page, etc. that represents this particular instance within the URL 
	stagingPrefix        VARCHAR2(20),
	status               VARCHAR2(50),    --  "active" or "inactive"  - the state of this registry entry. Note that the activation, deactivation and status entries do not have any relationship with the effectiveDate, expirationDate and isActive fields in the coding scheme itself.  In particular, it is possible to mark an "inactive" coding scheme as "active" (i.e. accessible) in the registry itself. 
	tag                  VARCHAR2(50),    --  Tag (e.g. production, test, etc.) associated with this release 
	lastUpdateDate       TIMESTAMP,    --  The date on which a record was last changed. 
	activationDate       TIMESTAMP,    --  Date on which a given entry will (or has) become active.  If absent, the record is considered inactive. 
	deactivationDate     TIMESTAMP,    --  Date on which a given record was (or will be) deactivated. 
	baseRevision         VARCHAR2(50),    --  The revision id of the resource when the revision record was created 
	fixedAtRevision      VARCHAR2(50),    --  If present, this version is "fixed" at this revision.  If the coding scheme isn't "at" the same revision, rollback must be done to reach this.  If absent,  this version is represented by the latest revision of the coding scheme, whatever it may be. 
	isLocked             CHAR(1),    --  True means that  updates are not allowed in the coding scheme. Default: false 
	dbSchemaVersion      VARCHAR2(50),    --  Version of LexGrid database schema structure. 
	dbSchemaDescription  VARCHAR2(255)    --  data base schema version description. 
)
;

COMMENT ON COLUMN @PREFIX@registry.registryGuid         IS 'global unique identifier of the resource loaded.'
;
COMMENT ON COLUMN @PREFIX@registry.resourceURI          IS 'URI of the resource loaded into lexEVS system.'
;
COMMENT ON COLUMN @PREFIX@registry.resourceVersion      IS 'The external version identifier that this particular instance represents.'
;
COMMENT ON COLUMN @PREFIX@registry.resourceType         IS 'The type this registry entry represents. Ex. CodingScheme, ValueDomain, PickList, History etc.'
;
COMMENT ON COLUMN @PREFIX@registry.dbURI                IS 'URL of the resource that contains this image'
;
COMMENT ON COLUMN @PREFIX@registry.dbName               IS 'name of the database. '
;
COMMENT ON COLUMN @PREFIX@registry.prefix               IS 'Instance identifier (e.g. database prefix, HTML sub-page, etc. that represents this particular instance within the URL'
;
COMMENT ON COLUMN @PREFIX@registry.status               IS '"active" or "inactive"  - the state of this registry entry. Note that the activation, deactivation and status entries do not have any relationship with the effectiveDate, expirationDate and isActive fields in the coding scheme itself.  In particular, it is possible to mark an "inactive" coding scheme as "active" (i.e. accessible) in the registry itself.'
;
COMMENT ON COLUMN @PREFIX@registry.tag                  IS 'Tag (e.g. production, test, etc.) associated with this release'
;
COMMENT ON COLUMN @PREFIX@registry.lastUpdateDate       IS 'The date on which a record was last changed.'
;
COMMENT ON COLUMN @PREFIX@registry.activationDate       IS 'Date on which a given entry will (or has) become active.  If absent, the record is considered inactive.'
;
COMMENT ON COLUMN @PREFIX@registry.deactivationDate     IS 'Date on which a given record was (or will be) deactivated.'
;
COMMENT ON COLUMN @PREFIX@registry.baseRevision         IS 'The revision id of the resource when the revision record was created'
;
COMMENT ON COLUMN @PREFIX@registry.fixedAtRevision      IS 'If present, this version is "fixed" at this revision.  If the coding scheme isn''t "at" the same revision, rollback must be done to reach this.  If absent,  this version is represented by the latest revision of the coding scheme, whatever it may be.'
;
COMMENT ON COLUMN @PREFIX@registry.isLocked             IS 'True means that  updates are not allowed in the coding scheme. Default: false'
;
COMMENT ON COLUMN @PREFIX@registry.dbSchemaVersion      IS 'Version of LexGrid database schema structure.'
;
COMMENT ON COLUMN @PREFIX@registry.dbSchemaDescription  IS 'data base schema version description.'
;

CREATE TABLE @PREFIX@registryMetaData
(
	id                        CHAR(1),
	lastUpdateTime            TIMESTAMP,
	lastUsedDBIdentifer       VARCHAR2(50),
	lastUsedHistoryIdentifer  VARCHAR2(50)
)
;



--  Create Primary Key Constraints 
ALTER TABLE @PREFIX@registry ADD CONSTRAINT PK_registry 
	PRIMARY KEY (registryGuid)
;


--  Create Indexes 
ALTER TABLE @PREFIX@registry
	ADD CONSTRAINT UQ_registry UNIQUE (resourceURI, resourceVersion, resourceType)
;
