--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.5.850
--   Created On : Thursday, 22 April, 2010 
--   DBMS       : Oracle 
--   -------------------------------------------------- 




--  Create Tables 
CREATE TABLE @PREFIX@registry
(
	registryGuid         VARCHAR2(36) NOT NULL,    --  global unique identifier of the resource loaded. 
	resourceURI          VARCHAR2(250),    --  URI of the resource loaded into lexEVS system. 
	resourceVersion      VARCHAR2(50),    --  The external version identifier that this particular instance represents. 
	resourceType         VARCHAR2(50),    --  The type this registry entry represents. Ex. CodingScheme, ValueDomain, PickList, History etc. 
	dbURI                VARCHAR2(250),    --  URL of the resource that contains this image 
	dbName               VARCHAR2(50),    --  name of the database.  
	prefix               VARCHAR2(20),    --  Instance identifier (e.g. database prefix, HTML sub-page, etc. that represents this particular instance within the URL 
	stagingPrefix        VARCHAR2(20),
	status               VARCHAR2(50),    --  "active" or "inactive"  - the state of this registry entry. Note that the activation, deactivation and status entries do not have any relationship with the effectiveDate, expirationDate and isActive fields in the coding scheme itself.  In particular, it is possible to mark an "inactive" coding scheme as "active" (i.e. accessible) in the registry itself. 
	tag                  VARCHAR2(50),    --  Tag (e.g. production, test, etc.) associated with this release 
	lastUpdateDate       TIMESTAMP,    --  The date on which a record was last changed. 
	activationDate       TIMESTAMP,    --  Date on which a given entry will (or has) become active.  If absent, the record is considered inactive. 
	deactivationDate     TIMESTAMP,    --  Date on which a given record was (or will be) deactivated. 
	baseRevision         VARCHAR2(50),    --  The revision id of the resource when the revision record was created 
	fixedAtRevision      VARCHAR2(50),    --  If present, this version is "fixed" at this revision.  If the coding scheme isn't "at" the same revision, rollback must be done to reach this.  If absent,  this version is represented by the latest revision of the coding scheme, whatever it may be. 
	isLocked             CHAR(1),    --  True means that  updates are not allowed in the coding scheme. Default: false 
	dbSchemaVersion      VARCHAR2(50),    --  Version of LexGrid database schema structure. 
	dbSchemaDescription  VARCHAR2(255)    --  data base schema version description. 
)
;

COMMENT ON COLUMN @PREFIX@registry.registryGuid         IS 'global unique identifier of the resource loaded.'
;
COMMENT ON COLUMN @PREFIX@registry.resourceURI          IS 'URI of the resource loaded into lexEVS system.'
;
COMMENT ON COLUMN @PREFIX@registry.resourceVersion      IS 'The external version identifier that this particular instance represents.'
;
COMMENT ON COLUMN @PREFIX@registry.resourceType         IS 'The type this registry entry represents. Ex. CodingScheme, ValueDomain, PickList, History etc.'
;
COMMENT ON COLUMN @PREFIX@registry.dbURI                IS 'URL of the resource that contains this image'
;
COMMENT ON COLUMN @PREFIX@registry.dbName               IS 'name of the database. '
;
COMMENT ON COLUMN @PREFIX@registry.prefix               IS 'Instance identifier (e.g. database prefix, HTML sub-page, etc. that represents this particular instance within the URL'
;
COMMENT ON COLUMN @PREFIX@registry.status               IS '"active" or "inactive"  - the state of this registry entry. Note that the activation, deactivation and status entries do not have any relationship with the effectiveDate, expirationDate and isActive fields in the coding scheme itself.  In particular, it is possible to mark an "inactive" coding scheme as "active" (i.e. accessible) in the registry itself.'
;
COMMENT ON COLUMN @PREFIX@registry.tag                  IS 'Tag (e.g. production, test, etc.) associated with this release'
;
COMMENT ON COLUMN @PREFIX@registry.lastUpdateDate       IS 'The date on which a record was last changed.'
;
COMMENT ON COLUMN @PREFIX@registry.activationDate       IS 'Date on which a given entry will (or has) become active.  If absent, the record is considered inactive.'
;
COMMENT ON COLUMN @PREFIX@registry.deactivationDate     IS 'Date on which a given record was (or will be) deactivated.'
;
COMMENT ON COLUMN @PREFIX@registry.baseRevision         IS 'The revision id of the resource when the revision record was created'
;
COMMENT ON COLUMN @PREFIX@registry.fixedAtRevision      IS 'If present, this version is "fixed" at this revision.  If the coding scheme isn''t "at" the same revision, rollback must be done to reach this.  If absent,  this version is represented by the latest revision of the coding scheme, whatever it may be.'
;
COMMENT ON COLUMN @PREFIX@registry.isLocked             IS 'True means that  updates are not allowed in the coding scheme. Default: false'
;
COMMENT ON COLUMN @PREFIX@registry.dbSchemaVersion      IS 'Version of LexGrid database schema structure.'
;
COMMENT ON COLUMN @PREFIX@registry.dbSchemaDescription  IS 'data base schema version description.'
;

CREATE TABLE @PREFIX@registryMetaData
(
	id                        char(1),
	lastUpdateTime            TIMESTAMP,
	lastUsedDBIdentifer       VARCHAR2(50),
	lastUsedHistoryIdentifer  VARCHAR2(50)
)
;



--  Create Primary Key Constraints 
ALTER TABLE @PREFIX@registry ADD CONSTRAINT PK_registry 
	PRIMARY KEY (registryGuid)
;


--  Create Indexes 
ALTER TABLE @PREFIX@registry
	ADD CONSTRAINT UQ_registry UNIQUE (resourceURI, resourceVersion, resourceType)
;


CREATE TABLE @PREFIX@revision
(
	revisionGuid        VARCHAR2(36) NOT NULL,    --  Global unique identifier for revision table entry. 
	releaseGuid         VARCHAR2(36),    --  Foreign key to the GUID of systemRelease table. 
	revisionId          VARCHAR2(50) NOT NULL,    --  The unique identifier of a given revision supplied by the source. The order of the revision is determined by the revAppliedDate.  
	changeAgent         VARCHAR2(50),    --  The local identifiers of the source(s) that participated in this particular change. changeAgent must match a local id of a supportedSource in the corresponding mappings section. 
	revisionDate        TIMESTAMP,    --  The end date for which this version is operative (considered commited).  
	revAppliedDate      TIMESTAMP NOT NULL,    --  The data and time on which the revision is applied into the lexEVS system. 
	editOrder           NUMBER(18),    --  The relative order that this revision is to be applied if in a systemRelease.  
	changeInstructions  CLOB,    --  A human or machine readable set of instructions on how to apply this change 
	description         CLOB    --  Description of the revision contents. 
)
;

COMMENT ON TABLE @PREFIX@revision IS 'An ordered collection of state changes that define the transformation of a set of resources from one consistent state to another.'
;
COMMENT ON COLUMN @PREFIX@revision.revisionGuid        IS 'Global unique identifier for revision table entry.'
;
COMMENT ON COLUMN @PREFIX@revision.releaseGuid         IS 'Foreign key to the GUID of systemRelease table.'
;
COMMENT ON COLUMN @PREFIX@revision.revisionId          IS 'The unique identifier of a given revision supplied by the source. The order of the revision is determined by the revAppliedDate. '
;
COMMENT ON COLUMN @PREFIX@revision.changeAgent         IS 'The local identifiers of the source(s) that participated in this particular change. changeAgent must match a local id of a supportedSource in the corresponding mappings section.'
;
COMMENT ON COLUMN @PREFIX@revision.revisionDate        IS 'The end date for which this version is operative (considered commited). '
;
COMMENT ON COLUMN @PREFIX@revision.revAppliedDate      IS 'The data and time on which the revision is applied into the lexEVS system.'
;
COMMENT ON COLUMN @PREFIX@revision.editOrder           IS 'The relative order that this revision is to be applied if in a systemRelease. '
;
COMMENT ON COLUMN @PREFIX@revision.changeInstructions  IS 'A human or machine readable set of instructions on how to apply this change'
;
COMMENT ON COLUMN @PREFIX@revision.description         IS 'Description of the revision contents.'
;

ALTER TABLE @PREFIX@revision ADD CONSTRAINT PK_revision 
	PRIMARY KEY (revisionGuid)
;

CREATE TABLE @PREFIX@systemRelease
(
	releaseGuid     VARCHAR2(36) NOT NULL,    --  Global unique identifier for systemRelease table. 
	releaseURI      VARCHAR2(250) NOT NULL,    --  The official URI of a given systemRelease. 
	releaseId       VARCHAR2(50),    --  The label assigned to a given  release by the release agency. 
	releaseDate     TIMESTAMP NOT NULL,    --  The official release data and time of a given release. 
	basedOnRelease  VARCHAR2(250),    --  The URI of the release that logically preceeds this release. 
	releaseAgency   VARCHAR2(250),    --  The URI of the agency responsible for this release. 
	description     CLOB    --  Description of the release contents. 
)
;

COMMENT ON TABLE @PREFIX@systemRelease IS 'Table holds the information about the different releases applied to the lexGrid system (if any). A collection of coding schemes, value domains, pick lists and/or revision records that are released as a unit. This table is common across database. It doesn''t inherit the table prefixes.'
;
COMMENT ON COLUMN @PREFIX@systemRelease.releaseGuid     IS 'Global unique identifier for systemRelease table.'
;
COMMENT ON COLUMN @PREFIX@systemRelease.releaseURI      IS 'The official URI of a given systemRelease.'
;
COMMENT ON COLUMN @PREFIX@systemRelease.releaseId       IS 'The label assigned to a given  release by the release agency.'
;
COMMENT ON COLUMN @PREFIX@systemRelease.releaseDate     IS 'The official release data and time of a given release.'
;
COMMENT ON COLUMN @PREFIX@systemRelease.basedOnRelease  IS 'The URI of the release that logically preceeds this release.'
;
COMMENT ON COLUMN @PREFIX@systemRelease.releaseAgency   IS 'The URI of the agency responsible for this release.'
;
COMMENT ON COLUMN @PREFIX@systemRelease.description     IS 'Description of the release contents.'
;

ALTER TABLE @PREFIX@systemRelease ADD CONSTRAINT PK_systemRelease 
	PRIMARY KEY (releaseGuid)
;
