--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.5.850
--   Created On : Thursday, 03 June, 2010 
--   DBMS       : PostgreSQL 
--   -------------------------------------------------- 

--  Create Tables 


CREATE TABLE @PREFIX@nciHistSystemRelease ( 
	releaseGuid varchar(36) NOT NULL,
	codingSchemeUri varchar(250) NOT NULL,
	releaseId varchar(50) NOT NULL,
	releaseURI varchar(250) NOT NULL,
	basedOnRelease varchar(250),
	releaseDate timestamp NOT NULL,
	releaseAgency varchar(250) NOT NULL,
	description TEXT
)
;

CREATE TABLE @PREFIX@nciHist ( 
	ncitHistGuid varchar(36) NOT NULL,
	releaseGuid varchar(36) NOT NULL,
	entityCode varchar(100) NOT NULL,
	conceptName varchar NOT NULL,
	editAction varchar(10) NOT NULL,
	editDate timestamp NOT NULL,
	referenceCode varchar(100),
	referenceName varchar
)
;

ALTER TABLE @PREFIX@nciHistSystemRelease ADD CONSTRAINT @PREFIX@PK_nciHistSystemRelease 
	PRIMARY KEY (releaseGuid)
;

ALTER TABLE @PREFIX@nciHist ADD CONSTRAINT PK_nciHist 
	PRIMARY KEY (ncitHistGuid)
;

ALTER TABLE @PREFIX@nciHist ADD CONSTRAINT @PREFIX@FK_nciHist
	FOREIGN KEY (releaseGuid) REFERENCES @PREFIX@nciHistSystemRelease (releaseGuid)
ON DELETE CASCADE
;

--  Create Indexes 
CREATE INDEX idx_ncitHist
ON @PREFIX@nciHist (entityCode, editAction)
;

CREATE INDEX idx_editDate
ON @PREFIX@nciHist (editDate)
;

CREATE INDEX idx_referenceCode
ON @PREFIX@nciHist (referenceCode)
;

ALTER TABLE @PREFIX@nciHistSystemRelease
	ADD CONSTRAINT UQ_ncih_sysRel UNIQUE (releaseId, releaseURI)
;

CREATE INDEX idx_releaseId
ON @PREFIX@systemRelease (releaseId)
;

CREATE INDEX idx_releaseDate
ON @PREFIX@systemRelease (releaseDate)
;