
package org.lexgrid.loader.rrf.model;
// Generated Feb 24, 2009 8:40:05 PM by Hibernate Tools 3.2.2.GA



/**
 * MrconsoId generated by hbm2java
 */
public class Mrconso  implements java.io.Serializable {


     private String cui;
     private String lat;
     private String ts;
     private String lui;
     private String stt;
     private String sui;
     private String ispref;
     private String aui;
     private String saui;
     private String scui;
     private String sdui;
     private String sab;
     private String tty;
     private String code;
     private String str;
     private String srl;
     private String suppress;
     private String cvf;

    public Mrconso() {
    }

    public Mrconso(String cui, String lat, String ts, String lui, String stt, String sui, String ispref, String aui, String saui, String scui, String sdui, String sab, String tty, String code, String str, String srl, String suppress, String cvf) {
       this.cui = cui;
       this.lat = lat;
       this.ts = ts;
       this.lui = lui;
       this.stt = stt;
       this.sui = sui;
       this.ispref = ispref;
       this.aui = aui;
       this.saui = saui;
       this.scui = scui;
       this.sdui = sdui;
       this.sab = sab;
       this.tty = tty;
       this.code = code;
       this.str = str;
       this.srl = srl;
       this.suppress = suppress;
       this.cvf = cvf;
    }
   
    public String getCui() {
        return this.cui;
    }
    
    public void setCui(String cui) {
        this.cui = cui;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getTs() {
        return this.ts;
    }
    
    public void setTs(String ts) {
        this.ts = ts;
    }
    public String getLui() {
        return this.lui;
    }
    
    public void setLui(String lui) {
        this.lui = lui;
    }
    public String getStt() {
        return this.stt;
    }
    
    public void setStt(String stt) {
        this.stt = stt;
    }
    public String getSui() {
        return this.sui;
    }
    
    public void setSui(String sui) {
        this.sui = sui;
    }
    public String getIspref() {
        return this.ispref;
    }
    
    public void setIspref(String ispref) {
        this.ispref = ispref;
    }
    public String getAui() {
        return this.aui;
    }
    
    public void setAui(String aui) {
        this.aui = aui;
    }
    public String getSaui() {
        return this.saui;
    }
    
    public void setSaui(String saui) {
        this.saui = saui;
    }
    public String getScui() {
        return this.scui;
    }
    
    public void setScui(String scui) {
        this.scui = scui;
    }
    public String getSdui() {
        return this.sdui;
    }
    
    public void setSdui(String sdui) {
        this.sdui = sdui;
    }
    public String getSab() {
        return this.sab;
    }
    
    public void setSab(String sab) {
        this.sab = sab;
    }
    public String getTty() {
        return this.tty;
    }
    
    public void setTty(String tty) {
        this.tty = tty;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getStr() {
        return this.str;
    }
    
    public void setStr(String str) {
        this.str = str;
    }
    public String getSrl() {
        return this.srl;
    }
    
    public void setSrl(String srl) {
        this.srl = srl;
    }
    public String getSuppress() {
        return this.suppress;
    }
    
    public void setSuppress(String suppress) {
        this.suppress = suppress;
    }
    public String getCvf() {
        return this.cvf;
    }
    
    public void setCvf(String cvf) {
        this.cvf = cvf;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mrconso) ) return false;
		 Mrconso castOther = ( Mrconso ) other; 
         
		 return ( (this.getCui()==castOther.getCui()) || ( this.getCui()!=null && castOther.getCui()!=null && this.getCui().equals(castOther.getCui()) ) )
 && ( (this.getLat()==castOther.getLat()) || ( this.getLat()!=null && castOther.getLat()!=null && this.getLat().equals(castOther.getLat()) ) )
 && ( (this.getTs()==castOther.getTs()) || ( this.getTs()!=null && castOther.getTs()!=null && this.getTs().equals(castOther.getTs()) ) )
 && ( (this.getLui()==castOther.getLui()) || ( this.getLui()!=null && castOther.getLui()!=null && this.getLui().equals(castOther.getLui()) ) )
 && ( (this.getStt()==castOther.getStt()) || ( this.getStt()!=null && castOther.getStt()!=null && this.getStt().equals(castOther.getStt()) ) )
 && ( (this.getSui()==castOther.getSui()) || ( this.getSui()!=null && castOther.getSui()!=null && this.getSui().equals(castOther.getSui()) ) )
 && ( (this.getIspref()==castOther.getIspref()) || ( this.getIspref()!=null && castOther.getIspref()!=null && this.getIspref().equals(castOther.getIspref()) ) )
 && ( (this.getAui()==castOther.getAui()) || ( this.getAui()!=null && castOther.getAui()!=null && this.getAui().equals(castOther.getAui()) ) )
 && ( (this.getSaui()==castOther.getSaui()) || ( this.getSaui()!=null && castOther.getSaui()!=null && this.getSaui().equals(castOther.getSaui()) ) )
 && ( (this.getScui()==castOther.getScui()) || ( this.getScui()!=null && castOther.getScui()!=null && this.getScui().equals(castOther.getScui()) ) )
 && ( (this.getSdui()==castOther.getSdui()) || ( this.getSdui()!=null && castOther.getSdui()!=null && this.getSdui().equals(castOther.getSdui()) ) )
 && ( (this.getSab()==castOther.getSab()) || ( this.getSab()!=null && castOther.getSab()!=null && this.getSab().equals(castOther.getSab()) ) )
 && ( (this.getTty()==castOther.getTty()) || ( this.getTty()!=null && castOther.getTty()!=null && this.getTty().equals(castOther.getTty()) ) )
 && ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getStr()==castOther.getStr()) || ( this.getStr()!=null && castOther.getStr()!=null && this.getStr().equals(castOther.getStr()) ) )
 && ( (this.getSrl()==castOther.getSrl()) || ( this.getSrl()!=null && castOther.getSrl()!=null && this.getSrl().equals(castOther.getSrl()) ) )
 && ( (this.getSuppress()==castOther.getSuppress()) || ( this.getSuppress()!=null && castOther.getSuppress()!=null && this.getSuppress().equals(castOther.getSuppress()) ) )
 && ( (this.getCvf()==castOther.getCvf()) || ( this.getCvf()!=null && castOther.getCvf()!=null && this.getCvf().equals(castOther.getCvf()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCui() == null ? 0 : this.getCui().hashCode() );
         result = 37 * result + ( getLat() == null ? 0 : this.getLat().hashCode() );
         result = 37 * result + ( getTs() == null ? 0 : this.getTs().hashCode() );
         result = 37 * result + ( getLui() == null ? 0 : this.getLui().hashCode() );
         result = 37 * result + ( getStt() == null ? 0 : this.getStt().hashCode() );
         result = 37 * result + ( getSui() == null ? 0 : this.getSui().hashCode() );
         result = 37 * result + ( getIspref() == null ? 0 : this.getIspref().hashCode() );
         result = 37 * result + ( getAui() == null ? 0 : this.getAui().hashCode() );
         result = 37 * result + ( getSaui() == null ? 0 : this.getSaui().hashCode() );
         result = 37 * result + ( getScui() == null ? 0 : this.getScui().hashCode() );
         result = 37 * result + ( getSdui() == null ? 0 : this.getSdui().hashCode() );
         result = 37 * result + ( getSab() == null ? 0 : this.getSab().hashCode() );
         result = 37 * result + ( getTty() == null ? 0 : this.getTty().hashCode() );
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getStr() == null ? 0 : this.getStr().hashCode() );
         result = 37 * result + ( getSrl() == null ? 0 : this.getSrl().hashCode() );
         result = 37 * result + ( getSuppress() == null ? 0 : this.getSuppress().hashCode() );
         result = 37 * result + ( getCvf() == null ? 0 : this.getCvf().hashCode() );
         return result;
   }   


}