
package org.lexgrid.loader.rrf.model;
// Generated Feb 24, 2009 8:40:05 PM by Hibernate Tools 3.2.2.GA



/**
 * MrdefId generated by hbm2java
 */
public class Mrdef  implements java.io.Serializable {


     private String cui;
     private String aui;
     private String atui;
     private String satui;
     private String sab;
     private String def;
     private String suppress;
     private String cvf;

    public Mrdef() {
    }

    public Mrdef(String cui, String aui, String atui, String satui, String sab, String def, String suppress, String cvf) {
       this.cui = cui;
       this.aui = aui;
       this.atui = atui;
       this.satui = satui;
       this.sab = sab;
       this.def = def;
       this.suppress = suppress;
       this.cvf = cvf;
    }
   
    public String getCui() {
        return this.cui;
    }
    
    public void setCui(String cui) {
        this.cui = cui;
    }
    public String getAui() {
        return this.aui;
    }
    
    public void setAui(String aui) {
        this.aui = aui;
    }
    public String getAtui() {
        return this.atui;
    }
    
    public void setAtui(String atui) {
        this.atui = atui;
    }
    public String getSatui() {
        return this.satui;
    }
    
    public void setSatui(String satui) {
        this.satui = satui;
    }
    public String getSab() {
        return this.sab;
    }
    
    public void setSab(String sab) {
        this.sab = sab;
    }
    public String getDef() {
        return this.def;
    }
    
    public void setDef(String def) {
        this.def = def;
    }
    public String getSuppress() {
        return this.suppress;
    }
    
    public void setSuppress(String suppress) {
        this.suppress = suppress;
    }
    public String getCvf() {
        return this.cvf;
    }
    
    public void setCvf(String cvf) {
        this.cvf = cvf;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mrdef) ) return false;
		 Mrdef castOther = ( Mrdef ) other; 
         
		 return ( (this.getCui()==castOther.getCui()) || ( this.getCui()!=null && castOther.getCui()!=null && this.getCui().equals(castOther.getCui()) ) )
 && ( (this.getAui()==castOther.getAui()) || ( this.getAui()!=null && castOther.getAui()!=null && this.getAui().equals(castOther.getAui()) ) )
 && ( (this.getAtui()==castOther.getAtui()) || ( this.getAtui()!=null && castOther.getAtui()!=null && this.getAtui().equals(castOther.getAtui()) ) )
 && ( (this.getSatui()==castOther.getSatui()) || ( this.getSatui()!=null && castOther.getSatui()!=null && this.getSatui().equals(castOther.getSatui()) ) )
 && ( (this.getSab()==castOther.getSab()) || ( this.getSab()!=null && castOther.getSab()!=null && this.getSab().equals(castOther.getSab()) ) )
 && ( (this.getDef()==castOther.getDef()) || ( this.getDef()!=null && castOther.getDef()!=null && this.getDef().equals(castOther.getDef()) ) )
 && ( (this.getSuppress()==castOther.getSuppress()) || ( this.getSuppress()!=null && castOther.getSuppress()!=null && this.getSuppress().equals(castOther.getSuppress()) ) )
 && ( (this.getCvf()==castOther.getCvf()) || ( this.getCvf()!=null && castOther.getCvf()!=null && this.getCvf().equals(castOther.getCvf()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCui() == null ? 0 : this.getCui().hashCode() );
         result = 37 * result + ( getAui() == null ? 0 : this.getAui().hashCode() );
         result = 37 * result + ( getAtui() == null ? 0 : this.getAtui().hashCode() );
         result = 37 * result + ( getSatui() == null ? 0 : this.getSatui().hashCode() );
         result = 37 * result + ( getSab() == null ? 0 : this.getSab().hashCode() );
         result = 37 * result + ( getDef() == null ? 0 : this.getDef().hashCode() );
         result = 37 * result + ( getSuppress() == null ? 0 : this.getSuppress().hashCode() );
         result = 37 * result + ( getCvf() == null ? 0 : this.getCvf().hashCode() );
         return result;
   }   


}