
package org.lexgrid.loader.rrf.model;
// Generated Feb 24, 2009 8:40:05 PM by Hibernate Tools 3.2.2.GA



/**
 * MrdocId generated by hbm2java
 */
public class Mrdoc  implements java.io.Serializable {


     private String dockey;
     private String value;
     private String type;
     private String expl;

    public Mrdoc() {
    }

    public Mrdoc(String dockey, String value, String type, String expl) {
       this.dockey = dockey;
       this.value = value;
       this.type = type;
       this.expl = expl;
    }
   
    public String getDockey() {
        return this.dockey;
    }
    
    public void setDockey(String dockey) {
        this.dockey = dockey;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getExpl() {
        return this.expl;
    }
    
    public void setExpl(String expl) {
        this.expl = expl;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mrdoc) ) return false;
		 Mrdoc castOther = ( Mrdoc ) other; 
         
		 return ( (this.getDockey()==castOther.getDockey()) || ( this.getDockey()!=null && castOther.getDockey()!=null && this.getDockey().equals(castOther.getDockey()) ) )
 && ( (this.getValue()==castOther.getValue()) || ( this.getValue()!=null && castOther.getValue()!=null && this.getValue().equals(castOther.getValue()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getExpl()==castOther.getExpl()) || ( this.getExpl()!=null && castOther.getExpl()!=null && this.getExpl().equals(castOther.getExpl()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDockey() == null ? 0 : this.getDockey().hashCode() );
         result = 37 * result + ( getValue() == null ? 0 : this.getValue().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getExpl() == null ? 0 : this.getExpl().hashCode() );
         return result;
   }   


}