
package org.lexgrid.loader.rrf.model;
// Generated Feb 24, 2009 8:40:05 PM by Hibernate Tools 3.2.2.GA



/**
 * MrrankId generated by hbm2java
 */
public class Mrrank  implements java.io.Serializable {


     private String rank;
     private String sab;
     private String tty;
     private String suppress;

    public Mrrank() {
    }

    public Mrrank(String rank, String sab, String tty, String suppress) {
       this.rank = rank;
       this.sab = sab;
       this.tty = tty;
       this.suppress = suppress;
    }
   
    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }
    public String getSab() {
        return this.sab;
    }
    
    public void setSab(String sab) {
        this.sab = sab;
    }
    public String getTty() {
        return this.tty;
    }
    
    public void setTty(String tty) {
        this.tty = tty;
    }
    public String getSuppress() {
        return this.suppress;
    }
    
    public void setSuppress(String suppress) {
        this.suppress = suppress;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mrrank) ) return false;
		 Mrrank castOther = ( Mrrank ) other; 
         
		 return ( (this.getRank()==castOther.getRank()) || ( this.getRank()!=null && castOther.getRank()!=null && this.getRank().equals(castOther.getRank()) ) )
 && ( (this.getSab()==castOther.getSab()) || ( this.getSab()!=null && castOther.getSab()!=null && this.getSab().equals(castOther.getSab()) ) )
 && ( (this.getTty()==castOther.getTty()) || ( this.getTty()!=null && castOther.getTty()!=null && this.getTty().equals(castOther.getTty()) ) )
 && ( (this.getSuppress()==castOther.getSuppress()) || ( this.getSuppress()!=null && castOther.getSuppress()!=null && this.getSuppress().equals(castOther.getSuppress()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRank() == null ? 0 : this.getRank().hashCode() );
         result = 37 * result + ( getSab() == null ? 0 : this.getSab().hashCode() );
         result = 37 * result + ( getTty() == null ? 0 : this.getTty().hashCode() );
         result = 37 * result + ( getSuppress() == null ? 0 : this.getSuppress().hashCode() );
         return result;
   }   


}