
package org.lexgrid.loader.rrf.model;
// Generated Feb 24, 2009 8:40:05 PM by Hibernate Tools 3.2.2.GA



/**
 * MrrelId generated by hbm2java
 */
public class Mrrel  implements java.io.Serializable {


     private String cui1;
     private String aui1;
     private String stype1;
     private String rel;
     private String cui2;
     private String aui2;
     private String stype2;
     private String rela;
     private String rui;
     private String srui;
     private String sab;
     private String sl;
     private String rg;
     private String dir;
     private String suppress;
     private String cvf;

    public Mrrel() {
    }

    public Mrrel(String cui1, String aui1, String stype1, String rel, String cui2, String aui2, String stype2, String rela, String rui, String srui, String sab, String sl, String rg, String dir, String suppress, String cvf) {
       this.cui1 = cui1;
       this.aui1 = aui1;
       this.stype1 = stype1;
       this.rel = rel;
       this.cui2 = cui2;
       this.aui2 = aui2;
       this.stype2 = stype2;
       this.rela = rela;
       this.rui = rui;
       this.srui = srui;
       this.sab = sab;
       this.sl = sl;
       this.rg = rg;
       this.dir = dir;
       this.suppress = suppress;
       this.cvf = cvf;
    }
   
    public String getCui1() {
        return this.cui1;
    }
    
    public void setCui1(String cui1) {
        this.cui1 = cui1;
    }
    public String getAui1() {
        return this.aui1;
    }
    
    public void setAui1(String aui1) {
        this.aui1 = aui1;
    }
    public String getStype1() {
        return this.stype1;
    }
    
    public void setStype1(String stype1) {
        this.stype1 = stype1;
    }
    public String getRel() {
        return this.rel;
    }
    
    public void setRel(String rel) {
        this.rel = rel;
    }
    public String getCui2() {
        return this.cui2;
    }
    
    public void setCui2(String cui2) {
        this.cui2 = cui2;
    }
    public String getAui2() {
        return this.aui2;
    }
    
    public void setAui2(String aui2) {
        this.aui2 = aui2;
    }
    public String getStype2() {
        return this.stype2;
    }
    
    public void setStype2(String stype2) {
        this.stype2 = stype2;
    }
    public String getRela() {
        return this.rela;
    }
    
    public void setRela(String rela) {
        this.rela = rela;
    }
    public String getRui() {
        return this.rui;
    }
    
    public void setRui(String rui) {
        this.rui = rui;
    }
    public String getSrui() {
        return this.srui;
    }
    
    public void setSrui(String srui) {
        this.srui = srui;
    }
    public String getSab() {
        return this.sab;
    }
    
    public void setSab(String sab) {
        this.sab = sab;
    }
    public String getSl() {
        return this.sl;
    }
    
    public void setSl(String sl) {
        this.sl = sl;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getDir() {
        return this.dir;
    }
    
    public void setDir(String dir) {
        this.dir = dir;
    }
    public String getSuppress() {
        return this.suppress;
    }
    
    public void setSuppress(String suppress) {
        this.suppress = suppress;
    }
    public String getCvf() {
        return this.cvf;
    }
    
    public void setCvf(String cvf) {
        this.cvf = cvf;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mrrel) ) return false;
		 Mrrel castOther = ( Mrrel ) other; 
         
		 return ( (this.getCui1()==castOther.getCui1()) || ( this.getCui1()!=null && castOther.getCui1()!=null && this.getCui1().equals(castOther.getCui1()) ) )
 && ( (this.getAui1()==castOther.getAui1()) || ( this.getAui1()!=null && castOther.getAui1()!=null && this.getAui1().equals(castOther.getAui1()) ) )
 && ( (this.getStype1()==castOther.getStype1()) || ( this.getStype1()!=null && castOther.getStype1()!=null && this.getStype1().equals(castOther.getStype1()) ) )
 && ( (this.getRel()==castOther.getRel()) || ( this.getRel()!=null && castOther.getRel()!=null && this.getRel().equals(castOther.getRel()) ) )
 && ( (this.getCui2()==castOther.getCui2()) || ( this.getCui2()!=null && castOther.getCui2()!=null && this.getCui2().equals(castOther.getCui2()) ) )
 && ( (this.getAui2()==castOther.getAui2()) || ( this.getAui2()!=null && castOther.getAui2()!=null && this.getAui2().equals(castOther.getAui2()) ) )
 && ( (this.getStype2()==castOther.getStype2()) || ( this.getStype2()!=null && castOther.getStype2()!=null && this.getStype2().equals(castOther.getStype2()) ) )
 && ( (this.getRela()==castOther.getRela()) || ( this.getRela()!=null && castOther.getRela()!=null && this.getRela().equals(castOther.getRela()) ) )
 && ( (this.getRui()==castOther.getRui()) || ( this.getRui()!=null && castOther.getRui()!=null && this.getRui().equals(castOther.getRui()) ) )
 && ( (this.getSrui()==castOther.getSrui()) || ( this.getSrui()!=null && castOther.getSrui()!=null && this.getSrui().equals(castOther.getSrui()) ) )
 && ( (this.getSab()==castOther.getSab()) || ( this.getSab()!=null && castOther.getSab()!=null && this.getSab().equals(castOther.getSab()) ) )
 && ( (this.getSl()==castOther.getSl()) || ( this.getSl()!=null && castOther.getSl()!=null && this.getSl().equals(castOther.getSl()) ) )
 && ( (this.getRg()==castOther.getRg()) || ( this.getRg()!=null && castOther.getRg()!=null && this.getRg().equals(castOther.getRg()) ) )
 && ( (this.getDir()==castOther.getDir()) || ( this.getDir()!=null && castOther.getDir()!=null && this.getDir().equals(castOther.getDir()) ) )
 && ( (this.getSuppress()==castOther.getSuppress()) || ( this.getSuppress()!=null && castOther.getSuppress()!=null && this.getSuppress().equals(castOther.getSuppress()) ) )
 && ( (this.getCvf()==castOther.getCvf()) || ( this.getCvf()!=null && castOther.getCvf()!=null && this.getCvf().equals(castOther.getCvf()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCui1() == null ? 0 : this.getCui1().hashCode() );
         result = 37 * result + ( getAui1() == null ? 0 : this.getAui1().hashCode() );
         result = 37 * result + ( getStype1() == null ? 0 : this.getStype1().hashCode() );
         result = 37 * result + ( getRel() == null ? 0 : this.getRel().hashCode() );
         result = 37 * result + ( getCui2() == null ? 0 : this.getCui2().hashCode() );
         result = 37 * result + ( getAui2() == null ? 0 : this.getAui2().hashCode() );
         result = 37 * result + ( getStype2() == null ? 0 : this.getStype2().hashCode() );
         result = 37 * result + ( getRela() == null ? 0 : this.getRela().hashCode() );
         result = 37 * result + ( getRui() == null ? 0 : this.getRui().hashCode() );
         result = 37 * result + ( getSrui() == null ? 0 : this.getSrui().hashCode() );
         result = 37 * result + ( getSab() == null ? 0 : this.getSab().hashCode() );
         result = 37 * result + ( getSl() == null ? 0 : this.getSl().hashCode() );
         result = 37 * result + ( getRg() == null ? 0 : this.getRg().hashCode() );
         result = 37 * result + ( getDir() == null ? 0 : this.getDir().hashCode() );
         result = 37 * result + ( getSuppress() == null ? 0 : this.getSuppress().hashCode() );
         result = 37 * result + ( getCvf() == null ? 0 : this.getCvf().hashCode() );
         return result;
   }   


}