
package org.lexgrid.loader.rrf.model;
// Generated Feb 24, 2009 8:40:05 PM by Hibernate Tools 3.2.2.GA



/**
 * MrsabId generated by hbm2java
 */
public class Mrsab  implements java.io.Serializable {


     private String vcui;
     private String rcui;
     private String vsab;
     private String rsab;
     private String son;
     private String sf;
     private String sver;
     private String vstart;
     private String vend;
     private String imeta;
     private String rmeta;
     private String slc;
     private String scc;
     private String srl;
     private String tfr;
     private String cfr;
     private String cxty;
     private String ttyl;
     private String atnl;
     private String lat;
     private String cenc;
     private String curver;
     private String sabin;
     private String ssn;
     private String scit;

    public Mrsab() {
    }

    public Mrsab(String vcui, String rcui, String vsab, String rsab, String son, String sf, String sver, String vstart, String vend, String imeta, String rmeta, String slc, String scc, String srl, String tfr, String cfr, String cxty, String ttyl, String atnl, String lat, String cenc, String curver, String sabin, String ssn, String scit) {
       this.vcui = vcui;
       this.rcui = rcui;
       this.vsab = vsab;
       this.rsab = rsab;
       this.son = son;
       this.sf = sf;
       this.sver = sver;
       this.vstart = vstart;
       this.vend = vend;
       this.imeta = imeta;
       this.rmeta = rmeta;
       this.slc = slc;
       this.scc = scc;
       this.srl = srl;
       this.tfr = tfr;
       this.cfr = cfr;
       this.cxty = cxty;
       this.ttyl = ttyl;
       this.atnl = atnl;
       this.lat = lat;
       this.cenc = cenc;
       this.curver = curver;
       this.sabin = sabin;
       this.ssn = ssn;
       this.scit = scit;
    }
   
    public String getVcui() {
        return this.vcui;
    }
    
    public void setVcui(String vcui) {
        this.vcui = vcui;
    }
    public String getRcui() {
        return this.rcui;
    }
    
    public void setRcui(String rcui) {
        this.rcui = rcui;
    }
    public String getVsab() {
        return this.vsab;
    }
    
    public void setVsab(String vsab) {
        this.vsab = vsab;
    }
    public String getRsab() {
        return this.rsab;
    }
    
    public void setRsab(String rsab) {
        this.rsab = rsab;
    }
    public String getSon() {
        return this.son;
    }
    
    public void setSon(String son) {
        this.son = son;
    }
    public String getSf() {
        return this.sf;
    }
    
    public void setSf(String sf) {
        this.sf = sf;
    }
    public String getSver() {
        return this.sver;
    }
    
    public void setSver(String sver) {
        this.sver = sver;
    }
    public String getVstart() {
        return this.vstart;
    }
    
    public void setVstart(String vstart) {
        this.vstart = vstart;
    }
    public String getVend() {
        return this.vend;
    }
    
    public void setVend(String vend) {
        this.vend = vend;
    }
    public String getImeta() {
        return this.imeta;
    }
    
    public void setImeta(String imeta) {
        this.imeta = imeta;
    }
    public String getRmeta() {
        return this.rmeta;
    }
    
    public void setRmeta(String rmeta) {
        this.rmeta = rmeta;
    }
    public String getSlc() {
        return this.slc;
    }
    
    public void setSlc(String slc) {
        this.slc = slc;
    }
    public String getScc() {
        return this.scc;
    }
    
    public void setScc(String scc) {
        this.scc = scc;
    }
    public String getSrl() {
        return this.srl;
    }
    
    public void setSrl(String srl) {
        this.srl = srl;
    }
    public String getTfr() {
        return this.tfr;
    }
    
    public void setTfr(String tfr) {
        this.tfr = tfr;
    }
    public String getCfr() {
        return this.cfr;
    }
    
    public void setCfr(String cfr) {
        this.cfr = cfr;
    }
    public String getCxty() {
        return this.cxty;
    }
    
    public void setCxty(String cxty) {
        this.cxty = cxty;
    }
    public String getTtyl() {
        return this.ttyl;
    }
    
    public void setTtyl(String ttyl) {
        this.ttyl = ttyl;
    }
    public String getAtnl() {
        return this.atnl;
    }
    
    public void setAtnl(String atnl) {
        this.atnl = atnl;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getCenc() {
        return this.cenc;
    }
    
    public void setCenc(String cenc) {
        this.cenc = cenc;
    }
    public String getCurver() {
        return this.curver;
    }
    
    public void setCurver(String curver) {
        this.curver = curver;
    }
    public String getSabin() {
        return this.sabin;
    }
    
    public void setSabin(String sabin) {
        this.sabin = sabin;
    }
    public String getSsn() {
        return this.ssn;
    }
    
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }
    public String getScit() {
        return this.scit;
    }
    
    public void setScit(String scit) {
        this.scit = scit;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mrsab) ) return false;
		 Mrsab castOther = ( Mrsab ) other; 
         
		 return ( (this.getVcui()==castOther.getVcui()) || ( this.getVcui()!=null && castOther.getVcui()!=null && this.getVcui().equals(castOther.getVcui()) ) )
 && ( (this.getRcui()==castOther.getRcui()) || ( this.getRcui()!=null && castOther.getRcui()!=null && this.getRcui().equals(castOther.getRcui()) ) )
 && ( (this.getVsab()==castOther.getVsab()) || ( this.getVsab()!=null && castOther.getVsab()!=null && this.getVsab().equals(castOther.getVsab()) ) )
 && ( (this.getRsab()==castOther.getRsab()) || ( this.getRsab()!=null && castOther.getRsab()!=null && this.getRsab().equals(castOther.getRsab()) ) )
 && ( (this.getSon()==castOther.getSon()) || ( this.getSon()!=null && castOther.getSon()!=null && this.getSon().equals(castOther.getSon()) ) )
 && ( (this.getSf()==castOther.getSf()) || ( this.getSf()!=null && castOther.getSf()!=null && this.getSf().equals(castOther.getSf()) ) )
 && ( (this.getSver()==castOther.getSver()) || ( this.getSver()!=null && castOther.getSver()!=null && this.getSver().equals(castOther.getSver()) ) )
 && ( (this.getVstart()==castOther.getVstart()) || ( this.getVstart()!=null && castOther.getVstart()!=null && this.getVstart().equals(castOther.getVstart()) ) )
 && ( (this.getVend()==castOther.getVend()) || ( this.getVend()!=null && castOther.getVend()!=null && this.getVend().equals(castOther.getVend()) ) )
 && ( (this.getImeta()==castOther.getImeta()) || ( this.getImeta()!=null && castOther.getImeta()!=null && this.getImeta().equals(castOther.getImeta()) ) )
 && ( (this.getRmeta()==castOther.getRmeta()) || ( this.getRmeta()!=null && castOther.getRmeta()!=null && this.getRmeta().equals(castOther.getRmeta()) ) )
 && ( (this.getSlc()==castOther.getSlc()) || ( this.getSlc()!=null && castOther.getSlc()!=null && this.getSlc().equals(castOther.getSlc()) ) )
 && ( (this.getScc()==castOther.getScc()) || ( this.getScc()!=null && castOther.getScc()!=null && this.getScc().equals(castOther.getScc()) ) )
 && ( (this.getSrl()==castOther.getSrl()) || ( this.getSrl()!=null && castOther.getSrl()!=null && this.getSrl().equals(castOther.getSrl()) ) )
 && ( (this.getTfr()==castOther.getTfr()) || ( this.getTfr()!=null && castOther.getTfr()!=null && this.getTfr().equals(castOther.getTfr()) ) )
 && ( (this.getCfr()==castOther.getCfr()) || ( this.getCfr()!=null && castOther.getCfr()!=null && this.getCfr().equals(castOther.getCfr()) ) )
 && ( (this.getCxty()==castOther.getCxty()) || ( this.getCxty()!=null && castOther.getCxty()!=null && this.getCxty().equals(castOther.getCxty()) ) )
 && ( (this.getTtyl()==castOther.getTtyl()) || ( this.getTtyl()!=null && castOther.getTtyl()!=null && this.getTtyl().equals(castOther.getTtyl()) ) )
 && ( (this.getAtnl()==castOther.getAtnl()) || ( this.getAtnl()!=null && castOther.getAtnl()!=null && this.getAtnl().equals(castOther.getAtnl()) ) )
 && ( (this.getLat()==castOther.getLat()) || ( this.getLat()!=null && castOther.getLat()!=null && this.getLat().equals(castOther.getLat()) ) )
 && ( (this.getCenc()==castOther.getCenc()) || ( this.getCenc()!=null && castOther.getCenc()!=null && this.getCenc().equals(castOther.getCenc()) ) )
 && ( (this.getCurver()==castOther.getCurver()) || ( this.getCurver()!=null && castOther.getCurver()!=null && this.getCurver().equals(castOther.getCurver()) ) )
 && ( (this.getSabin()==castOther.getSabin()) || ( this.getSabin()!=null && castOther.getSabin()!=null && this.getSabin().equals(castOther.getSabin()) ) )
 && ( (this.getSsn()==castOther.getSsn()) || ( this.getSsn()!=null && castOther.getSsn()!=null && this.getSsn().equals(castOther.getSsn()) ) )
 && ( (this.getScit()==castOther.getScit()) || ( this.getScit()!=null && castOther.getScit()!=null && this.getScit().equals(castOther.getScit()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVcui() == null ? 0 : this.getVcui().hashCode() );
         result = 37 * result + ( getRcui() == null ? 0 : this.getRcui().hashCode() );
         result = 37 * result + ( getVsab() == null ? 0 : this.getVsab().hashCode() );
         result = 37 * result + ( getRsab() == null ? 0 : this.getRsab().hashCode() );
         result = 37 * result + ( getSon() == null ? 0 : this.getSon().hashCode() );
         result = 37 * result + ( getSf() == null ? 0 : this.getSf().hashCode() );
         result = 37 * result + ( getSver() == null ? 0 : this.getSver().hashCode() );
         result = 37 * result + ( getVstart() == null ? 0 : this.getVstart().hashCode() );
         result = 37 * result + ( getVend() == null ? 0 : this.getVend().hashCode() );
         result = 37 * result + ( getImeta() == null ? 0 : this.getImeta().hashCode() );
         result = 37 * result + ( getRmeta() == null ? 0 : this.getRmeta().hashCode() );
         result = 37 * result + ( getSlc() == null ? 0 : this.getSlc().hashCode() );
         result = 37 * result + ( getScc() == null ? 0 : this.getScc().hashCode() );
         result = 37 * result + ( getSrl() == null ? 0 : this.getSrl().hashCode() );
         result = 37 * result + ( getTfr() == null ? 0 : this.getTfr().hashCode() );
         result = 37 * result + ( getCfr() == null ? 0 : this.getCfr().hashCode() );
         result = 37 * result + ( getCxty() == null ? 0 : this.getCxty().hashCode() );
         result = 37 * result + ( getTtyl() == null ? 0 : this.getTtyl().hashCode() );
         result = 37 * result + ( getAtnl() == null ? 0 : this.getAtnl().hashCode() );
         result = 37 * result + ( getLat() == null ? 0 : this.getLat().hashCode() );
         result = 37 * result + ( getCenc() == null ? 0 : this.getCenc().hashCode() );
         result = 37 * result + ( getCurver() == null ? 0 : this.getCurver().hashCode() );
         result = 37 * result + ( getSabin() == null ? 0 : this.getSabin().hashCode() );
         result = 37 * result + ( getSsn() == null ? 0 : this.getSsn().hashCode() );
         result = 37 * result + ( getScit() == null ? 0 : this.getScit().hashCode() );
         return result;
   }   


}