
package org.lexgrid.loader.rrf.model;
// Generated Feb 24, 2009 8:40:05 PM by Hibernate Tools 3.2.2.GA



/**
 * MrstyId generated by hbm2java
 */
public class Mrsty  implements java.io.Serializable {


     private String cui;
     private String tui;
     private String stn;
     private String sty;
     private String atui;
     private String cvf;

    public Mrsty() {
    }

    public Mrsty(String cui, String tui, String stn, String sty, String atui, String cvf) {
       this.cui = cui;
       this.tui = tui;
       this.stn = stn;
       this.sty = sty;
       this.atui = atui;
       this.cvf = cvf;
    }
   
    public String getCui() {
        return this.cui;
    }
    
    public void setCui(String cui) {
        this.cui = cui;
    }
    public String getTui() {
        return this.tui;
    }
    
    public void setTui(String tui) {
        this.tui = tui;
    }
    public String getStn() {
        return this.stn;
    }
    
    public void setStn(String stn) {
        this.stn = stn;
    }
    public String getSty() {
        return this.sty;
    }
    
    public void setSty(String sty) {
        this.sty = sty;
    }
    public String getAtui() {
        return this.atui;
    }
    
    public void setAtui(String atui) {
        this.atui = atui;
    }
    public String getCvf() {
        return this.cvf;
    }
    
    public void setCvf(String cvf) {
        this.cvf = cvf;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mrsty) ) return false;
		 Mrsty castOther = ( Mrsty ) other; 
         
		 return ( (this.getCui()==castOther.getCui()) || ( this.getCui()!=null && castOther.getCui()!=null && this.getCui().equals(castOther.getCui()) ) )
 && ( (this.getTui()==castOther.getTui()) || ( this.getTui()!=null && castOther.getTui()!=null && this.getTui().equals(castOther.getTui()) ) )
 && ( (this.getStn()==castOther.getStn()) || ( this.getStn()!=null && castOther.getStn()!=null && this.getStn().equals(castOther.getStn()) ) )
 && ( (this.getSty()==castOther.getSty()) || ( this.getSty()!=null && castOther.getSty()!=null && this.getSty().equals(castOther.getSty()) ) )
 && ( (this.getAtui()==castOther.getAtui()) || ( this.getAtui()!=null && castOther.getAtui()!=null && this.getAtui().equals(castOther.getAtui()) ) )
 && ( (this.getCvf()==castOther.getCvf()) || ( this.getCvf()!=null && castOther.getCvf()!=null && this.getCvf().equals(castOther.getCvf()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCui() == null ? 0 : this.getCui().hashCode() );
         result = 37 * result + ( getTui() == null ? 0 : this.getTui().hashCode() );
         result = 37 * result + ( getStn() == null ? 0 : this.getStn().hashCode() );
         result = 37 * result + ( getSty() == null ? 0 : this.getSty().hashCode() );
         result = 37 * result + ( getAtui() == null ? 0 : this.getAtui().hashCode() );
         result = 37 * result + ( getCvf() == null ? 0 : this.getCvf().hashCode() );
         return result;
   }   


}