package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * Association generated by hbm2java
 */
public class Association  implements java.io.Serializable {


     private AssociationId id;
     private String associationName;
     private String forwardName;
     private String reverseName;
     private String inverseId;
     private Boolean isNavigable;
     private Boolean isTransitive;
     private Boolean isAntiTransitive;
     private Boolean isSymmetric;
     private Boolean isAntiSymmetric;
     private Boolean isReflexive;
     private Boolean isAntiReflexive;
     private Boolean isFunctional;
     private Boolean isReverseFunctional;
     private String entityDescription;

    public Association() {
    }

	
    public Association(AssociationId id, String associationName, String forwardName) {
        this.id = id;
        this.associationName = associationName;
        this.forwardName = forwardName;
    }
    public Association(AssociationId id, String associationName, String forwardName, String reverseName, String inverseId, Boolean isNavigable, Boolean isTransitive, Boolean isAntiTransitive, Boolean isSymmetric, Boolean isAntiSymmetric, Boolean isReflexive, Boolean isAntiReflexive, Boolean isFunctional, Boolean isReverseFunctional, String entityDescription) {
       this.id = id;
       this.associationName = associationName;
       this.forwardName = forwardName;
       this.reverseName = reverseName;
       this.inverseId = inverseId;
       this.isNavigable = isNavigable;
       this.isTransitive = isTransitive;
       this.isAntiTransitive = isAntiTransitive;
       this.isSymmetric = isSymmetric;
       this.isAntiSymmetric = isAntiSymmetric;
       this.isReflexive = isReflexive;
       this.isAntiReflexive = isAntiReflexive;
       this.isFunctional = isFunctional;
       this.isReverseFunctional = isReverseFunctional;
       this.entityDescription = entityDescription;
    }
   
    public AssociationId getId() {
        return this.id;
    }
    
    public void setId(AssociationId id) {
        this.id = id;
    }
    public String getAssociationName() {
        return this.associationName;
    }
    
    public void setAssociationName(String associationName) {
        this.associationName = associationName;
    }
    public String getForwardName() {
        return this.forwardName;
    }
    
    public void setForwardName(String forwardName) {
        this.forwardName = forwardName;
    }
    public String getReverseName() {
        return this.reverseName;
    }
    
    public void setReverseName(String reverseName) {
        this.reverseName = reverseName;
    }
    public String getInverseId() {
        return this.inverseId;
    }
    
    public void setInverseId(String inverseId) {
        this.inverseId = inverseId;
    }
    public Boolean getIsNavigable() {
        return this.isNavigable;
    }
    
    public void setIsNavigable(Boolean isNavigable) {
        this.isNavigable = isNavigable;
    }
    public Boolean getIsTransitive() {
        return this.isTransitive;
    }
    
    public void setIsTransitive(Boolean isTransitive) {
        this.isTransitive = isTransitive;
    }
    public Boolean getIsAntiTransitive() {
        return this.isAntiTransitive;
    }
    
    public void setIsAntiTransitive(Boolean isAntiTransitive) {
        this.isAntiTransitive = isAntiTransitive;
    }
    public Boolean getIsSymmetric() {
        return this.isSymmetric;
    }
    
    public void setIsSymmetric(Boolean isSymmetric) {
        this.isSymmetric = isSymmetric;
    }
    public Boolean getIsAntiSymmetric() {
        return this.isAntiSymmetric;
    }
    
    public void setIsAntiSymmetric(Boolean isAntiSymmetric) {
        this.isAntiSymmetric = isAntiSymmetric;
    }
    public Boolean getIsReflexive() {
        return this.isReflexive;
    }
    
    public void setIsReflexive(Boolean isReflexive) {
        this.isReflexive = isReflexive;
    }
    public Boolean getIsAntiReflexive() {
        return this.isAntiReflexive;
    }
    
    public void setIsAntiReflexive(Boolean isAntiReflexive) {
        this.isAntiReflexive = isAntiReflexive;
    }
    public Boolean getIsFunctional() {
        return this.isFunctional;
    }
    
    public void setIsFunctional(Boolean isFunctional) {
        this.isFunctional = isFunctional;
    }
    public Boolean getIsReverseFunctional() {
        return this.isReverseFunctional;
    }
    
    public void setIsReverseFunctional(Boolean isReverseFunctional) {
        this.isReverseFunctional = isReverseFunctional;
    }
    public String getEntityDescription() {
        return this.entityDescription;
    }
    
    public void setEntityDescription(String entityDescription) {
        this.entityDescription = entityDescription;
    }




}


