package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * AssociationId generated by hbm2java
 */
public class AssociationId  implements java.io.Serializable {


     private String codingSchemeName;
     private String containerName;
     private String entityCodeNamespace;
     private String entityCode;

    public AssociationId() {
    }

    public AssociationId(String codingSchemeName, String containerName, String entityCodeNamespace, String entityCode) {
       this.codingSchemeName = codingSchemeName;
       this.containerName = containerName;
       this.entityCodeNamespace = entityCodeNamespace;
       this.entityCode = entityCode;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getContainerName() {
        return this.containerName;
    }
    
    public void setContainerName(String containerName) {
        this.containerName = containerName;
    }
    public String getEntityCodeNamespace() {
        return this.entityCodeNamespace;
    }
    
    public void setEntityCodeNamespace(String entityCodeNamespace) {
        this.entityCodeNamespace = entityCodeNamespace;
    }
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AssociationId) ) return false;
		 AssociationId castOther = ( AssociationId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getContainerName()==castOther.getContainerName()) || ( this.getContainerName()!=null && castOther.getContainerName()!=null && this.getContainerName().equals(castOther.getContainerName()) ) )
 && ( (this.getEntityCodeNamespace()==castOther.getEntityCodeNamespace()) || ( this.getEntityCodeNamespace()!=null && castOther.getEntityCodeNamespace()!=null && this.getEntityCodeNamespace().equals(castOther.getEntityCodeNamespace()) ) )
 && ( (this.getEntityCode()==castOther.getEntityCode()) || ( this.getEntityCode()!=null && castOther.getEntityCode()!=null && this.getEntityCode().equals(castOther.getEntityCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getContainerName() == null ? 0 : this.getContainerName().hashCode() );
         result = 37 * result + ( getEntityCodeNamespace() == null ? 0 : this.getEntityCodeNamespace().hashCode() );
         result = 37 * result + ( getEntityCode() == null ? 0 : this.getEntityCode().hashCode() );
         return result;
   }   


}


