package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * CodingSchemeMultiAttribId generated by hbm2java
 */
public class CodingSchemeMultiAttribId  implements java.io.Serializable {


     private String codingSchemeName;
     private String typeName;
     private String attributeValue;

    public CodingSchemeMultiAttribId() {
    }

    public CodingSchemeMultiAttribId(String codingSchemeName, String typeName, String attributeValue) {
       this.codingSchemeName = codingSchemeName;
       this.typeName = typeName;
       this.attributeValue = attributeValue;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public String getAttributeValue() {
        return this.attributeValue;
    }
    
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CodingSchemeMultiAttribId) ) return false;
		 CodingSchemeMultiAttribId castOther = ( CodingSchemeMultiAttribId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getTypeName()==castOther.getTypeName()) || ( this.getTypeName()!=null && castOther.getTypeName()!=null && this.getTypeName().equals(castOther.getTypeName()) ) )
 && ( (this.getAttributeValue()==castOther.getAttributeValue()) || ( this.getAttributeValue()!=null && castOther.getAttributeValue()!=null && this.getAttributeValue().equals(castOther.getAttributeValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getTypeName() == null ? 0 : this.getTypeName().hashCode() );
         result = 37 * result + ( getAttributeValue() == null ? 0 : this.getAttributeValue().hashCode() );
         return result;
   }   


}


