package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * CodingSchemePropMultiAttrib generated by hbm2java
 */
public class CodingSchemePropMultiAttrib  implements java.io.Serializable {


     private CodingSchemePropMultiAttribId id;
     private String val1;
     private String val2;

    public CodingSchemePropMultiAttrib() {
    }

	
    public CodingSchemePropMultiAttrib(CodingSchemePropMultiAttribId id) {
        this.id = id;
    }
    public CodingSchemePropMultiAttrib(CodingSchemePropMultiAttribId id, String val1, String val2) {
       this.id = id;
       this.val1 = val1;
       this.val2 = val2;
    }
   
    public CodingSchemePropMultiAttribId getId() {
        return this.id;
    }
    
    public void setId(CodingSchemePropMultiAttribId id) {
        this.id = id;
    }
    public String getVal1() {
        return this.val1;
    }
    
    public void setVal1(String val1) {
        this.val1 = val1;
    }
    public String getVal2() {
        return this.val2;
    }
    
    public void setVal2(String val2) {
        this.val2 = val2;
    }




}


