package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * CodingSchemeSupportedAttrib generated by hbm2java
 */
public class CodingSchemeSupportedAttrib  implements java.io.Serializable {


     private CodingSchemeSupportedAttribId id;
     private String uri;
     private String val2;

    public CodingSchemeSupportedAttrib() {
    }

	
    public CodingSchemeSupportedAttrib(CodingSchemeSupportedAttribId id) {
        this.id = id;
    }
    public CodingSchemeSupportedAttrib(CodingSchemeSupportedAttribId id, String uri, String val2) {
       this.id = id;
       this.uri = uri;
       this.val2 = val2;
    }
   
    public CodingSchemeSupportedAttribId getId() {
        return this.id;
    }
    
    public void setId(CodingSchemeSupportedAttribId id) {
        this.id = id;
    }
    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }
    public String getVal2() {
        return this.val2;
    }
    
    public void setVal2(String val2) {
        this.val2 = val2;
    }




}


