package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * CodingScheme generated by hbm2java
 */
public class CodingScheme  implements java.io.Serializable {


     private String codingSchemeName;
     private String codingSchemeUri;
     private String representsVersion;
     private String formalName;
     private String defaultLanguage;
     private Long approxNumConcepts;
     private Boolean isActive;
     private Long entryStateId;
     private String releaseUri;
     private String entityDescription;
     private String copyright;

    public CodingScheme() {
    }

	
    public CodingScheme(String codingSchemeName, String codingSchemeUri, String representsVersion) {
        this.codingSchemeName = codingSchemeName;
        this.codingSchemeUri = codingSchemeUri;
        this.representsVersion = representsVersion;
    }
    public CodingScheme(String codingSchemeName, String codingSchemeUri, String representsVersion, String formalName, String defaultLanguage, Long approxNumConcepts, Boolean isActive, Long entryStateId, String releaseUri, String entityDescription, String copyright) {
       this.codingSchemeName = codingSchemeName;
       this.codingSchemeUri = codingSchemeUri;
       this.representsVersion = representsVersion;
       this.formalName = formalName;
       this.defaultLanguage = defaultLanguage;
       this.approxNumConcepts = approxNumConcepts;
       this.isActive = isActive;
       this.entryStateId = entryStateId;
       this.releaseUri = releaseUri;
       this.entityDescription = entityDescription;
       this.copyright = copyright;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getCodingSchemeUri() {
        return this.codingSchemeUri;
    }
    
    public void setCodingSchemeUri(String codingSchemeUri) {
        this.codingSchemeUri = codingSchemeUri;
    }
    public String getRepresentsVersion() {
        return this.representsVersion;
    }
    
    public void setRepresentsVersion(String representsVersion) {
        this.representsVersion = representsVersion;
    }
    public String getFormalName() {
        return this.formalName;
    }
    
    public void setFormalName(String formalName) {
        this.formalName = formalName;
    }
    public String getDefaultLanguage() {
        return this.defaultLanguage;
    }
    
    public void setDefaultLanguage(String defaultLanguage) {
        this.defaultLanguage = defaultLanguage;
    }
    public Long getApproxNumConcepts() {
        return this.approxNumConcepts;
    }
    
    public void setApproxNumConcepts(Long approxNumConcepts) {
        this.approxNumConcepts = approxNumConcepts;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Long getEntryStateId() {
        return this.entryStateId;
    }
    
    public void setEntryStateId(Long entryStateId) {
        this.entryStateId = entryStateId;
    }
    public String getReleaseUri() {
        return this.releaseUri;
    }
    
    public void setReleaseUri(String releaseUri) {
        this.releaseUri = releaseUri;
    }
    public String getEntityDescription() {
        return this.entityDescription;
    }
    
    public void setEntityDescription(String entityDescription) {
        this.entityDescription = entityDescription;
    }
    public String getCopyright() {
        return this.copyright;
    }
    
    public void setCopyright(String copyright) {
        this.copyright = copyright;
    }




}


