package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * CodingSchemeSupportedAttribId generated by hbm2java
 */
public class CodingSchemeSupportedAttribId  implements java.io.Serializable {


     private String codingSchemeName;
     private String supportedAttributeTag;
     private String id;
     private String idValue;
     private String val1;

    public CodingSchemeSupportedAttribId() {
    }

    public CodingSchemeSupportedAttribId(String codingSchemeName, String supportedAttributeTag, String id, String idValue, String val1) {
       this.codingSchemeName = codingSchemeName;
       this.supportedAttributeTag = supportedAttributeTag;
       this.id = id;
       this.idValue = idValue;
       this.val1 = val1;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getSupportedAttributeTag() {
        return this.supportedAttributeTag;
    }
    
    public void setSupportedAttributeTag(String supportedAttributeTag) {
        this.supportedAttributeTag = supportedAttributeTag;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIdValue() {
        return this.idValue;
    }
    
    public void setIdValue(String idValue) {
        this.idValue = idValue;
    }
    public String getVal1() {
        return this.val1;
    }
    
    public void setVal1(String val1) {
        this.val1 = val1;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CodingSchemeSupportedAttribId) ) return false;
		 CodingSchemeSupportedAttribId castOther = ( CodingSchemeSupportedAttribId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getSupportedAttributeTag()==castOther.getSupportedAttributeTag()) || ( this.getSupportedAttributeTag()!=null && castOther.getSupportedAttributeTag()!=null && this.getSupportedAttributeTag().equals(castOther.getSupportedAttributeTag()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getIdValue()==castOther.getIdValue()) || ( this.getIdValue()!=null && castOther.getIdValue()!=null && this.getIdValue().equals(castOther.getIdValue()) ) )
 && ( (this.getVal1()==castOther.getVal1()) || ( this.getVal1()!=null && castOther.getVal1()!=null && this.getVal1().equals(castOther.getVal1()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getSupportedAttributeTag() == null ? 0 : this.getSupportedAttributeTag().hashCode() );
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getIdValue() == null ? 0 : this.getIdValue().hashCode() );
         result = 37 * result + ( getVal1() == null ? 0 : this.getVal1().hashCode() );
         return result;
   }   


}


