package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * CodingSchemeProp generated by hbm2java
 */
public class CodingSchemeProp  implements java.io.Serializable {


     private CodingSchemePropId id;
     private String propertyName;
     private String language;
     private String format;
     private Boolean isActive;
     private Long entryStateId;
     private String propertyValue;

    public CodingSchemeProp() {
    }

	
    public CodingSchemeProp(CodingSchemePropId id, String propertyName) {
        this.id = id;
        this.propertyName = propertyName;
    }
    public CodingSchemeProp(CodingSchemePropId id, String propertyName, String language, String format, Boolean isActive, Long entryStateId, String propertyValue) {
       this.id = id;
       this.propertyName = propertyName;
       this.language = language;
       this.format = format;
       this.isActive = isActive;
       this.entryStateId = entryStateId;
       this.propertyValue = propertyValue;
    }
   
    public CodingSchemePropId getId() {
        return this.id;
    }
    
    public void setId(CodingSchemePropId id) {
        this.id = id;
    }
    public String getPropertyName() {
        return this.propertyName;
    }
    
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Long getEntryStateId() {
        return this.entryStateId;
    }
    
    public void setEntryStateId(Long entryStateId) {
        this.entryStateId = entryStateId;
    }
    public String getPropertyValue() {
        return this.propertyValue;
    }
    
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }




}


