package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * CodingSchemePropId generated by hbm2java
 */
public class CodingSchemePropId  implements java.io.Serializable {


     private String codingSchemeName;
     private String propertyId;

    public CodingSchemePropId() {
    }

    public CodingSchemePropId(String codingSchemeName, String propertyId) {
       this.codingSchemeName = codingSchemeName;
       this.propertyId = propertyId;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CodingSchemePropId) ) return false;
		 CodingSchemePropId castOther = ( CodingSchemePropId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getPropertyId()==castOther.getPropertyId()) || ( this.getPropertyId()!=null && castOther.getPropertyId()!=null && this.getPropertyId().equals(castOther.getPropertyId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getPropertyId() == null ? 0 : this.getPropertyId().hashCode() );
         return result;
   }   


}


