package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * CodingSchemeMultiAttrib generated by hbm2java
 */
public class CodingSchemeMultiAttrib  implements java.io.Serializable {


     private CodingSchemeMultiAttribId id;
     private String val1;
     private String val2;

    public CodingSchemeMultiAttrib() {
    }

	
    public CodingSchemeMultiAttrib(CodingSchemeMultiAttribId id) {
        this.id = id;
    }
    public CodingSchemeMultiAttrib(CodingSchemeMultiAttribId id, String val1, String val2) {
       this.id = id;
       this.val1 = val1;
       this.val2 = val2;
    }
   
    public CodingSchemeMultiAttribId getId() {
        return this.id;
    }
    
    public void setId(CodingSchemeMultiAttribId id) {
        this.id = id;
    }
    public String getVal1() {
        return this.val1;
    }
    
    public void setVal1(String val1) {
        this.val1 = val1;
    }
    public String getVal2() {
        return this.val2;
    }
    
    public void setVal2(String val2) {
        this.val2 = val2;
    }




}


