package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityProperty generated by hbm2java
 */
public class EntityProperty  implements java.io.Serializable {


     private EntityPropertyId id;
     private String propertyType;
     private String propertyName;
     private String language;
     private String format;
     private Boolean isPreferred;
     private String degreeOfFidelity;
     private Boolean matchIfNoContext;
     private String representationalForm;
     private Boolean isActive;
     private Long entryStateId;
     private String propertyValue;

    public EntityProperty() {
    }

	
    public EntityProperty(EntityPropertyId id, String propertyName, String propertyValue) {
        this.id = id;
        this.propertyName = propertyName;
        this.propertyValue = propertyValue;
    }
    public EntityProperty(EntityPropertyId id, String propertyType, String propertyName, String language, String format, Boolean isPreferred, String degreeOfFidelity, Boolean matchIfNoContext, String representationalForm, Boolean isActive, Long entryStateId, String propertyValue) {
       this.id = id;
       this.propertyType = propertyType;
       this.propertyName = propertyName;
       this.language = language;
       this.format = format;
       this.isPreferred = isPreferred;
       this.degreeOfFidelity = degreeOfFidelity;
       this.matchIfNoContext = matchIfNoContext;
       this.representationalForm = representationalForm;
       this.isActive = isActive;
       this.entryStateId = entryStateId;
       this.propertyValue = propertyValue;
    }
   
    public EntityPropertyId getId() {
        return this.id;
    }
    
    public void setId(EntityPropertyId id) {
        this.id = id;
    }
    public String getPropertyType() {
        return this.propertyType;
    }
    
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType;
    }
    public String getPropertyName() {
        return this.propertyName;
    }
    
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public Boolean getIsPreferred() {
        return this.isPreferred;
    }
    
    public void setIsPreferred(Boolean isPreferred) {
        this.isPreferred = isPreferred;
    }
    public String getDegreeOfFidelity() {
        return this.degreeOfFidelity;
    }
    
    public void setDegreeOfFidelity(String degreeOfFidelity) {
        this.degreeOfFidelity = degreeOfFidelity;
    }
    public Boolean getMatchIfNoContext() {
        return this.matchIfNoContext;
    }
    
    public void setMatchIfNoContext(Boolean matchIfNoContext) {
        this.matchIfNoContext = matchIfNoContext;
    }
    public String getRepresentationalForm() {
        return this.representationalForm;
    }
    
    public void setRepresentationalForm(String representationalForm) {
        this.representationalForm = representationalForm;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Long getEntryStateId() {
        return this.entryStateId;
    }
    
    public void setEntryStateId(Long entryStateId) {
        this.entryStateId = entryStateId;
    }
    public String getPropertyValue() {
        return this.propertyValue;
    }
    
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }




}


