package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityAssnsToEntityTrId generated by hbm2java
 */
public class EntityAssnsToEntityTrId  implements java.io.Serializable {


     private String codingSchemeName;
     private String containerName;
     private String entityCodeNamespace;
     private String entityCode;
     private String sourceEntityCodeNamespace;
     private String sourceEntityCode;
     private String targetEntityCodeNamespace;
     private String targetEntityCode;

    public EntityAssnsToEntityTrId() {
    }

    public EntityAssnsToEntityTrId(String codingSchemeName, String containerName, String entityCodeNamespace, String entityCode, String sourceEntityCodeNamespace, String sourceEntityCode, String targetEntityCodeNamespace, String targetEntityCode) {
       this.codingSchemeName = codingSchemeName;
       this.containerName = containerName;
       this.entityCodeNamespace = entityCodeNamespace;
       this.entityCode = entityCode;
       this.sourceEntityCodeNamespace = sourceEntityCodeNamespace;
       this.sourceEntityCode = sourceEntityCode;
       this.targetEntityCodeNamespace = targetEntityCodeNamespace;
       this.targetEntityCode = targetEntityCode;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getContainerName() {
        return this.containerName;
    }
    
    public void setContainerName(String containerName) {
        this.containerName = containerName;
    }
    public String getEntityCodeNamespace() {
        return this.entityCodeNamespace;
    }
    
    public void setEntityCodeNamespace(String entityCodeNamespace) {
        this.entityCodeNamespace = entityCodeNamespace;
    }
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    public String getSourceEntityCodeNamespace() {
        return this.sourceEntityCodeNamespace;
    }
    
    public void setSourceEntityCodeNamespace(String sourceEntityCodeNamespace) {
        this.sourceEntityCodeNamespace = sourceEntityCodeNamespace;
    }
    public String getSourceEntityCode() {
        return this.sourceEntityCode;
    }
    
    public void setSourceEntityCode(String sourceEntityCode) {
        this.sourceEntityCode = sourceEntityCode;
    }
    public String getTargetEntityCodeNamespace() {
        return this.targetEntityCodeNamespace;
    }
    
    public void setTargetEntityCodeNamespace(String targetEntityCodeNamespace) {
        this.targetEntityCodeNamespace = targetEntityCodeNamespace;
    }
    public String getTargetEntityCode() {
        return this.targetEntityCode;
    }
    
    public void setTargetEntityCode(String targetEntityCode) {
        this.targetEntityCode = targetEntityCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntityAssnsToEntityTrId) ) return false;
		 EntityAssnsToEntityTrId castOther = ( EntityAssnsToEntityTrId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getContainerName()==castOther.getContainerName()) || ( this.getContainerName()!=null && castOther.getContainerName()!=null && this.getContainerName().equals(castOther.getContainerName()) ) )
 && ( (this.getEntityCodeNamespace()==castOther.getEntityCodeNamespace()) || ( this.getEntityCodeNamespace()!=null && castOther.getEntityCodeNamespace()!=null && this.getEntityCodeNamespace().equals(castOther.getEntityCodeNamespace()) ) )
 && ( (this.getEntityCode()==castOther.getEntityCode()) || ( this.getEntityCode()!=null && castOther.getEntityCode()!=null && this.getEntityCode().equals(castOther.getEntityCode()) ) )
 && ( (this.getSourceEntityCodeNamespace()==castOther.getSourceEntityCodeNamespace()) || ( this.getSourceEntityCodeNamespace()!=null && castOther.getSourceEntityCodeNamespace()!=null && this.getSourceEntityCodeNamespace().equals(castOther.getSourceEntityCodeNamespace()) ) )
 && ( (this.getSourceEntityCode()==castOther.getSourceEntityCode()) || ( this.getSourceEntityCode()!=null && castOther.getSourceEntityCode()!=null && this.getSourceEntityCode().equals(castOther.getSourceEntityCode()) ) )
 && ( (this.getTargetEntityCodeNamespace()==castOther.getTargetEntityCodeNamespace()) || ( this.getTargetEntityCodeNamespace()!=null && castOther.getTargetEntityCodeNamespace()!=null && this.getTargetEntityCodeNamespace().equals(castOther.getTargetEntityCodeNamespace()) ) )
 && ( (this.getTargetEntityCode()==castOther.getTargetEntityCode()) || ( this.getTargetEntityCode()!=null && castOther.getTargetEntityCode()!=null && this.getTargetEntityCode().equals(castOther.getTargetEntityCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getContainerName() == null ? 0 : this.getContainerName().hashCode() );
         result = 37 * result + ( getEntityCodeNamespace() == null ? 0 : this.getEntityCodeNamespace().hashCode() );
         result = 37 * result + ( getEntityCode() == null ? 0 : this.getEntityCode().hashCode() );
         result = 37 * result + ( getSourceEntityCodeNamespace() == null ? 0 : this.getSourceEntityCodeNamespace().hashCode() );
         result = 37 * result + ( getSourceEntityCode() == null ? 0 : this.getSourceEntityCode().hashCode() );
         result = 37 * result + ( getTargetEntityCodeNamespace() == null ? 0 : this.getTargetEntityCodeNamespace().hashCode() );
         result = 37 * result + ( getTargetEntityCode() == null ? 0 : this.getTargetEntityCode().hashCode() );
         return result;
   }   


}


