package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityPropertyMultiAttrib generated by hbm2java
 */
public class EntityPropertyMultiAttrib  implements java.io.Serializable {


     private EntityPropertyMultiAttribId id;
     private String qualifierType;
     private String val2;

    public EntityPropertyMultiAttrib() {
    }

	
    public EntityPropertyMultiAttrib(EntityPropertyMultiAttribId id) {
        this.id = id;
    }
    public EntityPropertyMultiAttrib(EntityPropertyMultiAttribId id, String qualifierType, String val2) {
       this.id = id;
       this.qualifierType = qualifierType;
       this.val2 = val2;
    }
   
    public EntityPropertyMultiAttribId getId() {
        return this.id;
    }
    
    public void setId(EntityPropertyMultiAttribId id) {
        this.id = id;
    }
    public String getQualifierType() {
        return this.qualifierType;
    }
    
    public void setQualifierType(String qualifierType) {
        this.qualifierType = qualifierType;
    }
    public String getVal2() {
        return this.val2;
    }
    
    public void setVal2(String val2) {
        this.val2 = val2;
    }




}


