package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityPropertyMultiAttribId generated by hbm2java
 */
public class EntityPropertyMultiAttribId  implements java.io.Serializable {


     private String codingSchemeName;
     private String entityCodeNamespace;
     private String entityCode;
     private String propertyId;
     private String typeName;
     private String attributeValue;
     private String val1;

    public EntityPropertyMultiAttribId() {
    }

    public EntityPropertyMultiAttribId(String codingSchemeName, String entityCodeNamespace, String entityCode, String propertyId, String typeName, String attributeValue, String val1) {
       this.codingSchemeName = codingSchemeName;
       this.entityCodeNamespace = entityCodeNamespace;
       this.entityCode = entityCode;
       this.propertyId = propertyId;
       this.typeName = typeName;
       this.attributeValue = attributeValue;
       this.val1 = val1;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getEntityCodeNamespace() {
        return this.entityCodeNamespace;
    }
    
    public void setEntityCodeNamespace(String entityCodeNamespace) {
        this.entityCodeNamespace = entityCodeNamespace;
    }
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    public String getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public String getAttributeValue() {
        return this.attributeValue;
    }
    
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }
    public String getVal1() {
        return this.val1;
    }
    
    public void setVal1(String val1) {
        this.val1 = val1;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntityPropertyMultiAttribId) ) return false;
		 EntityPropertyMultiAttribId castOther = ( EntityPropertyMultiAttribId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getEntityCodeNamespace()==castOther.getEntityCodeNamespace()) || ( this.getEntityCodeNamespace()!=null && castOther.getEntityCodeNamespace()!=null && this.getEntityCodeNamespace().equals(castOther.getEntityCodeNamespace()) ) )
 && ( (this.getEntityCode()==castOther.getEntityCode()) || ( this.getEntityCode()!=null && castOther.getEntityCode()!=null && this.getEntityCode().equals(castOther.getEntityCode()) ) )
 && ( (this.getPropertyId()==castOther.getPropertyId()) || ( this.getPropertyId()!=null && castOther.getPropertyId()!=null && this.getPropertyId().equals(castOther.getPropertyId()) ) )
 && ( (this.getTypeName()==castOther.getTypeName()) || ( this.getTypeName()!=null && castOther.getTypeName()!=null && this.getTypeName().equals(castOther.getTypeName()) ) )
 && ( (this.getAttributeValue()==castOther.getAttributeValue()) || ( this.getAttributeValue()!=null && castOther.getAttributeValue()!=null && this.getAttributeValue().equals(castOther.getAttributeValue()) ) )
 && ( (this.getVal1()==castOther.getVal1()) || ( this.getVal1()!=null && castOther.getVal1()!=null && this.getVal1().equals(castOther.getVal1()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getEntityCodeNamespace() == null ? 0 : this.getEntityCodeNamespace().hashCode() );
         result = 37 * result + ( getEntityCode() == null ? 0 : this.getEntityCode().hashCode() );
         result = 37 * result + ( getPropertyId() == null ? 0 : this.getPropertyId().hashCode() );
         result = 37 * result + ( getTypeName() == null ? 0 : this.getTypeName().hashCode() );
         result = 37 * result + ( getAttributeValue() == null ? 0 : this.getAttributeValue().hashCode() );
         result = 37 * result + ( getVal1() == null ? 0 : this.getVal1().hashCode() );
         return result;
   }   


}


