package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityAssnsToEqualsId generated by hbm2java
 */
public class EntityAssnsToEqualsId  implements java.io.Serializable {


     private String codingSchemeName;
     private String multiAttributesKey;
     private String qualifierName;
     private String qualifierValue;

    public EntityAssnsToEqualsId() {
    }

    public EntityAssnsToEqualsId(String codingSchemeName, String multiAttributesKey, String qualifierName, String qualifierValue) {
       this.codingSchemeName = codingSchemeName;
       this.multiAttributesKey = multiAttributesKey;
       this.qualifierName = qualifierName;
       this.qualifierValue = qualifierValue;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getMultiAttributesKey() {
        return this.multiAttributesKey;
    }
    
    public void setMultiAttributesKey(String multiAttributesKey) {
        this.multiAttributesKey = multiAttributesKey;
    }
    public String getQualifierName() {
        return this.qualifierName;
    }
    
    public void setQualifierName(String qualifierName) {
        this.qualifierName = qualifierName;
    }
    public String getQualifierValue() {
        return this.qualifierValue;
    }
    
    public void setQualifierValue(String qualifierValue) {
        this.qualifierValue = qualifierValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntityAssnsToEqualsId) ) return false;
		 EntityAssnsToEqualsId castOther = ( EntityAssnsToEqualsId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getMultiAttributesKey()==castOther.getMultiAttributesKey()) || ( this.getMultiAttributesKey()!=null && castOther.getMultiAttributesKey()!=null && this.getMultiAttributesKey().equals(castOther.getMultiAttributesKey()) ) )
 && ( (this.getQualifierName()==castOther.getQualifierName()) || ( this.getQualifierName()!=null && castOther.getQualifierName()!=null && this.getQualifierName().equals(castOther.getQualifierName()) ) )
 && ( (this.getQualifierValue()==castOther.getQualifierValue()) || ( this.getQualifierValue()!=null && castOther.getQualifierValue()!=null && this.getQualifierValue().equals(castOther.getQualifierValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getMultiAttributesKey() == null ? 0 : this.getMultiAttributesKey().hashCode() );
         result = 37 * result + ( getQualifierName() == null ? 0 : this.getQualifierName().hashCode() );
         result = 37 * result + ( getQualifierValue() == null ? 0 : this.getQualifierValue().hashCode() );
         return result;
   }   


}


