package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityAssnsToEntityTr generated by hbm2java
 */
public class EntityAssnsToEntityTr  implements java.io.Serializable {


     private EntityAssnsToEntityTrId id;

    public EntityAssnsToEntityTr() {
    }

    public EntityAssnsToEntityTr(EntityAssnsToEntityTrId id) {
       this.id = id;
    }
   
    public EntityAssnsToEntityTrId getId() {
        return this.id;
    }
    
    public void setId(EntityAssnsToEntityTrId id) {
        this.id = id;
    }




}


