package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityPropertyId generated by hbm2java
 */
public class EntityPropertyId  implements java.io.Serializable {


     private String codingSchemeName;
     private String entityCodeNamespace;
     private String entityCode;
     private String propertyId;

    public EntityPropertyId() {
    }

    public EntityPropertyId(String codingSchemeName, String entityCodeNamespace, String entityCode, String propertyId) {
       this.codingSchemeName = codingSchemeName;
       this.entityCodeNamespace = entityCodeNamespace;
       this.entityCode = entityCode;
       this.propertyId = propertyId;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getEntityCodeNamespace() {
        return this.entityCodeNamespace;
    }
    
    public void setEntityCodeNamespace(String entityCodeNamespace) {
        this.entityCodeNamespace = entityCodeNamespace;
    }
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    public String getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntityPropertyId) ) return false;
		 EntityPropertyId castOther = ( EntityPropertyId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getEntityCodeNamespace()==castOther.getEntityCodeNamespace()) || ( this.getEntityCodeNamespace()!=null && castOther.getEntityCodeNamespace()!=null && this.getEntityCodeNamespace().equals(castOther.getEntityCodeNamespace()) ) )
 && ( (this.getEntityCode()==castOther.getEntityCode()) || ( this.getEntityCode()!=null && castOther.getEntityCode()!=null && this.getEntityCode().equals(castOther.getEntityCode()) ) )
 && ( (this.getPropertyId()==castOther.getPropertyId()) || ( this.getPropertyId()!=null && castOther.getPropertyId()!=null && this.getPropertyId().equals(castOther.getPropertyId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getEntityCodeNamespace() == null ? 0 : this.getEntityCodeNamespace().hashCode() );
         result = 37 * result + ( getEntityCode() == null ? 0 : this.getEntityCode().hashCode() );
         result = 37 * result + ( getPropertyId() == null ? 0 : this.getPropertyId().hashCode() );
         return result;
   }   


}


