package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityPropertyLinksId generated by hbm2java
 */
public class EntityPropertyLinksId  implements java.io.Serializable {


     private String codingSchemeName;
     private String entityCodeNamespace;
     private String entityCode;
     private String sourcePropertyId;
     private String link;
     private String targetPropertyId;

    public EntityPropertyLinksId() {
    }

    public EntityPropertyLinksId(String codingSchemeName, String entityCodeNamespace, String entityCode, String sourcePropertyId, String link, String targetPropertyId) {
       this.codingSchemeName = codingSchemeName;
       this.entityCodeNamespace = entityCodeNamespace;
       this.entityCode = entityCode;
       this.sourcePropertyId = sourcePropertyId;
       this.link = link;
       this.targetPropertyId = targetPropertyId;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getEntityCodeNamespace() {
        return this.entityCodeNamespace;
    }
    
    public void setEntityCodeNamespace(String entityCodeNamespace) {
        this.entityCodeNamespace = entityCodeNamespace;
    }
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    public String getSourcePropertyId() {
        return this.sourcePropertyId;
    }
    
    public void setSourcePropertyId(String sourcePropertyId) {
        this.sourcePropertyId = sourcePropertyId;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getTargetPropertyId() {
        return this.targetPropertyId;
    }
    
    public void setTargetPropertyId(String targetPropertyId) {
        this.targetPropertyId = targetPropertyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntityPropertyLinksId) ) return false;
		 EntityPropertyLinksId castOther = ( EntityPropertyLinksId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getEntityCodeNamespace()==castOther.getEntityCodeNamespace()) || ( this.getEntityCodeNamespace()!=null && castOther.getEntityCodeNamespace()!=null && this.getEntityCodeNamespace().equals(castOther.getEntityCodeNamespace()) ) )
 && ( (this.getEntityCode()==castOther.getEntityCode()) || ( this.getEntityCode()!=null && castOther.getEntityCode()!=null && this.getEntityCode().equals(castOther.getEntityCode()) ) )
 && ( (this.getSourcePropertyId()==castOther.getSourcePropertyId()) || ( this.getSourcePropertyId()!=null && castOther.getSourcePropertyId()!=null && this.getSourcePropertyId().equals(castOther.getSourcePropertyId()) ) )
 && ( (this.getLink()==castOther.getLink()) || ( this.getLink()!=null && castOther.getLink()!=null && this.getLink().equals(castOther.getLink()) ) )
 && ( (this.getTargetPropertyId()==castOther.getTargetPropertyId()) || ( this.getTargetPropertyId()!=null && castOther.getTargetPropertyId()!=null && this.getTargetPropertyId().equals(castOther.getTargetPropertyId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getEntityCodeNamespace() == null ? 0 : this.getEntityCodeNamespace().hashCode() );
         result = 37 * result + ( getEntityCode() == null ? 0 : this.getEntityCode().hashCode() );
         result = 37 * result + ( getSourcePropertyId() == null ? 0 : this.getSourcePropertyId().hashCode() );
         result = 37 * result + ( getLink() == null ? 0 : this.getLink().hashCode() );
         result = 37 * result + ( getTargetPropertyId() == null ? 0 : this.getTargetPropertyId().hashCode() );
         return result;
   }   


}


