package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * Entity generated by hbm2java
 */
public class Entity  implements java.io.Serializable {


     private EntityId id;
     private Boolean isDefined;
     private Boolean isAnonymous;
     private Boolean isActive;
     private Long entryStateId;
     private String entityDescription;

    public Entity() {
    }

	
    public Entity(EntityId id) {
        this.id = id;
    }
    public Entity(EntityId id, Boolean isDefined, Boolean isAnonymous, Boolean isActive, Long entryStateId, String entityDescription) {
       this.id = id;
       this.isDefined = isDefined;
       this.isAnonymous = isAnonymous;
       this.isActive = isActive;
       this.entryStateId = entryStateId;
       this.entityDescription = entityDescription;
    }
   
    public EntityId getId() {
        return this.id;
    }
    
    public void setId(EntityId id) {
        this.id = id;
    }
    public Boolean getIsDefined() {
        return this.isDefined;
    }
    
    public void setIsDefined(Boolean isDefined) {
        this.isDefined = isDefined;
    }
    public Boolean getIsAnonymous() {
        return this.isAnonymous;
    }
    
    public void setIsAnonymous(Boolean isAnonymous) {
        this.isAnonymous = isAnonymous;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Long getEntryStateId() {
        return this.entryStateId;
    }
    
    public void setEntryStateId(Long entryStateId) {
        this.entryStateId = entryStateId;
    }
    public String getEntityDescription() {
        return this.entityDescription;
    }
    
    public void setEntityDescription(String entityDescription) {
        this.entityDescription = entityDescription;
    }




}


