package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityAssnsToEntity generated by hbm2java
 */
public class EntityAssnsToEntity  implements java.io.Serializable {


     private String multiAttributesKey;
     private String codingSchemeName;
     private String containerName;
     private String entityCodeNamespace;
     private String entityCode;
     private String sourceEntityCodeNamespace;
     private String sourceEntityCode;
     private String targetEntityCodeNamespace;
     private String targetEntityCode;
     private String associationInstanceId;
     private Boolean isDefining;
     private Boolean isInferred;
     private Boolean isActive;
     private Long entryStateId;

    public EntityAssnsToEntity() {
    }

	
    public EntityAssnsToEntity(String multiAttributesKey, String codingSchemeName, String containerName, String entityCodeNamespace, String entityCode, String sourceEntityCodeNamespace, String sourceEntityCode, String targetEntityCodeNamespace, String targetEntityCode) {
        this.multiAttributesKey = multiAttributesKey;
        this.codingSchemeName = codingSchemeName;
        this.containerName = containerName;
        this.entityCodeNamespace = entityCodeNamespace;
        this.entityCode = entityCode;
        this.sourceEntityCodeNamespace = sourceEntityCodeNamespace;
        this.sourceEntityCode = sourceEntityCode;
        this.targetEntityCodeNamespace = targetEntityCodeNamespace;
        this.targetEntityCode = targetEntityCode;
    }
    public EntityAssnsToEntity(String multiAttributesKey, String codingSchemeName, String containerName, String entityCodeNamespace, String entityCode, String sourceEntityCodeNamespace, String sourceEntityCode, String targetEntityCodeNamespace, String targetEntityCode, String associationInstanceId, Boolean isDefining, Boolean isInferred, Boolean isActive, Long entryStateId) {
       this.multiAttributesKey = multiAttributesKey;
       this.codingSchemeName = codingSchemeName;
       this.containerName = containerName;
       this.entityCodeNamespace = entityCodeNamespace;
       this.entityCode = entityCode;
       this.sourceEntityCodeNamespace = sourceEntityCodeNamespace;
       this.sourceEntityCode = sourceEntityCode;
       this.targetEntityCodeNamespace = targetEntityCodeNamespace;
       this.targetEntityCode = targetEntityCode;
       this.associationInstanceId = associationInstanceId;
       this.isDefining = isDefining;
       this.isInferred = isInferred;
       this.isActive = isActive;
       this.entryStateId = entryStateId;
    }
   
    public String getMultiAttributesKey() {
        return this.multiAttributesKey;
    }
    
    public void setMultiAttributesKey(String multiAttributesKey) {
        this.multiAttributesKey = multiAttributesKey;
    }
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getContainerName() {
        return this.containerName;
    }
    
    public void setContainerName(String containerName) {
        this.containerName = containerName;
    }
    public String getEntityCodeNamespace() {
        return this.entityCodeNamespace;
    }
    
    public void setEntityCodeNamespace(String entityCodeNamespace) {
        this.entityCodeNamespace = entityCodeNamespace;
    }
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    public String getSourceEntityCodeNamespace() {
        return this.sourceEntityCodeNamespace;
    }
    
    public void setSourceEntityCodeNamespace(String sourceEntityCodeNamespace) {
        this.sourceEntityCodeNamespace = sourceEntityCodeNamespace;
    }
    public String getSourceEntityCode() {
        return this.sourceEntityCode;
    }
    
    public void setSourceEntityCode(String sourceEntityCode) {
        this.sourceEntityCode = sourceEntityCode;
    }
    public String getTargetEntityCodeNamespace() {
        return this.targetEntityCodeNamespace;
    }
    
    public void setTargetEntityCodeNamespace(String targetEntityCodeNamespace) {
        this.targetEntityCodeNamespace = targetEntityCodeNamespace;
    }
    public String getTargetEntityCode() {
        return this.targetEntityCode;
    }
    
    public void setTargetEntityCode(String targetEntityCode) {
        this.targetEntityCode = targetEntityCode;
    }
    public String getAssociationInstanceId() {
        return this.associationInstanceId;
    }
    
    public void setAssociationInstanceId(String associationInstanceId) {
        this.associationInstanceId = associationInstanceId;
    }
    public Boolean getIsDefining() {
        return this.isDefining;
    }
    
    public void setIsDefining(Boolean isDefining) {
        this.isDefining = isDefining;
    }
    public Boolean getIsInferred() {
        return this.isInferred;
    }
    
    public void setIsInferred(Boolean isInferred) {
        this.isInferred = isInferred;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Long getEntryStateId() {
        return this.entryStateId;
    }
    
    public void setEntryStateId(Long entryStateId) {
        this.entryStateId = entryStateId;
    }




}


