package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityAssnsToDquals generated by hbm2java
 */
public class EntityAssnsToDquals  implements java.io.Serializable {


     private EntityAssnsToDqualsId id;
     private String qualifierValue;

    public EntityAssnsToDquals() {
    }

    public EntityAssnsToDquals(EntityAssnsToDqualsId id, String qualifierValue) {
       this.id = id;
       this.qualifierValue = qualifierValue;
    }
   
    public EntityAssnsToDqualsId getId() {
        return this.id;
    }
    
    public void setId(EntityAssnsToDqualsId id) {
        this.id = id;
    }
    public String getQualifierValue() {
        return this.qualifierValue;
    }
    
    public void setQualifierValue(String qualifierValue) {
        this.qualifierValue = qualifierValue;
    }




}


