package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityType generated by hbm2java
 */
public class EntityType  implements java.io.Serializable {


     private EntityTypeId id;

    public EntityType() {
    }

    public EntityType(EntityTypeId id) {
       this.id = id;
    }
   
    public EntityTypeId getId() {
        return this.id;
    }
    
    public void setId(EntityTypeId id) {
        this.id = id;
    }




}


