package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityAssnsToEquals generated by hbm2java
 */
public class EntityAssnsToEquals  implements java.io.Serializable {


     private EntityAssnsToEqualsId id;

    public EntityAssnsToEquals() {
    }

    public EntityAssnsToEquals(EntityAssnsToEqualsId id) {
       this.id = id;
    }
   
    public EntityAssnsToEqualsId getId() {
        return this.id;
    }
    
    public void setId(EntityAssnsToEqualsId id) {
        this.id = id;
    }




}


