package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * EntityPropertyLinks generated by hbm2java
 */
public class EntityPropertyLinks  implements java.io.Serializable {


     private EntityPropertyLinksId id;

    public EntityPropertyLinks() {
    }

    public EntityPropertyLinks(EntityPropertyLinksId id) {
       this.id = id;
    }
   
    public EntityPropertyLinksId getId() {
        return this.id;
    }
    
    public void setId(EntityPropertyLinksId id) {
        this.id = id;
    }




}


