package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * EntryState generated by hbm2java
 */
public class EntryState  implements java.io.Serializable {


     private long entryStateId;
     private String entryType;
     private String owner;
     private String status;
     private Date effectiveDate;
     private Date expirationDate;
     private String revisionId;
     private String prevRevisionId;
     private String changeType;
     private long relativeOrder;
     private Long prevEntryStateId;

    public EntryState() {
    }

	
    public EntryState(long entryStateId, String entryType, String changeType, long relativeOrder) {
        this.entryStateId = entryStateId;
        this.entryType = entryType;
        this.changeType = changeType;
        this.relativeOrder = relativeOrder;
    }
    public EntryState(long entryStateId, String entryType, String owner, String status, Date effectiveDate, Date expirationDate, String revisionId, String prevRevisionId, String changeType, long relativeOrder, Long prevEntryStateId) {
       this.entryStateId = entryStateId;
       this.entryType = entryType;
       this.owner = owner;
       this.status = status;
       this.effectiveDate = effectiveDate;
       this.expirationDate = expirationDate;
       this.revisionId = revisionId;
       this.prevRevisionId = prevRevisionId;
       this.changeType = changeType;
       this.relativeOrder = relativeOrder;
       this.prevEntryStateId = prevEntryStateId;
    }
   
    public long getEntryStateId() {
        return this.entryStateId;
    }
    
    public void setEntryStateId(long entryStateId) {
        this.entryStateId = entryStateId;
    }
    public String getEntryType() {
        return this.entryType;
    }
    
    public void setEntryType(String entryType) {
        this.entryType = entryType;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    public Date getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }
    public String getRevisionId() {
        return this.revisionId;
    }
    
    public void setRevisionId(String revisionId) {
        this.revisionId = revisionId;
    }
    public String getPrevRevisionId() {
        return this.prevRevisionId;
    }
    
    public void setPrevRevisionId(String prevRevisionId) {
        this.prevRevisionId = prevRevisionId;
    }
    public String getChangeType() {
        return this.changeType;
    }
    
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }
    public long getRelativeOrder() {
        return this.relativeOrder;
    }
    
    public void setRelativeOrder(long relativeOrder) {
        this.relativeOrder = relativeOrder;
    }
    public Long getPrevEntryStateId() {
        return this.prevEntryStateId;
    }
    
    public void setPrevEntryStateId(Long prevEntryStateId) {
        this.prevEntryStateId = prevEntryStateId;
    }




}


