package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * LexGridTableMetaDataId generated by hbm2java
 */
public class LexGridTableMetaDataId  implements java.io.Serializable {


     private String version;
     private String description;

    public LexGridTableMetaDataId() {
    }

	
    public LexGridTableMetaDataId(String version) {
        this.version = version;
    }
    public LexGridTableMetaDataId(String version, String description) {
       this.version = version;
       this.description = description;
    }
   
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LexGridTableMetaDataId) ) return false;
		 LexGridTableMetaDataId castOther = ( LexGridTableMetaDataId ) other; 
         
		 return ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         return result;
   }   


}


