package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * LexGridTableMetaData generated by hbm2java
 */
public class LexGridTableMetaData  implements java.io.Serializable {


     private LexGridTableMetaDataId id;

    public LexGridTableMetaData() {
    }

    public LexGridTableMetaData(LexGridTableMetaDataId id) {
       this.id = id;
    }
   
    public LexGridTableMetaDataId getId() {
        return this.id;
    }
    
    public void setId(LexGridTableMetaDataId id) {
        this.id = id;
    }




}


