package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * RelationId generated by hbm2java
 */
public class RelationId  implements java.io.Serializable {


     private String codingSchemeName;
     private String containerName;

    public RelationId() {
    }

    public RelationId(String codingSchemeName, String containerName) {
       this.codingSchemeName = codingSchemeName;
       this.containerName = containerName;
    }
   
    public String getCodingSchemeName() {
        return this.codingSchemeName;
    }
    
    public void setCodingSchemeName(String codingSchemeName) {
        this.codingSchemeName = codingSchemeName;
    }
    public String getContainerName() {
        return this.containerName;
    }
    
    public void setContainerName(String containerName) {
        this.containerName = containerName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelationId) ) return false;
		 RelationId castOther = ( RelationId ) other; 
         
		 return ( (this.getCodingSchemeName()==castOther.getCodingSchemeName()) || ( this.getCodingSchemeName()!=null && castOther.getCodingSchemeName()!=null && this.getCodingSchemeName().equals(castOther.getCodingSchemeName()) ) )
 && ( (this.getContainerName()==castOther.getContainerName()) || ( this.getContainerName()!=null && castOther.getContainerName()!=null && this.getContainerName().equals(castOther.getContainerName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodingSchemeName() == null ? 0 : this.getCodingSchemeName().hashCode() );
         result = 37 * result + ( getContainerName() == null ? 0 : this.getContainerName().hashCode() );
         return result;
   }   


}


