package org.LexGrid.persistence.model;
// Generated Jul 30, 2009 7:07:52 AM by Hibernate Tools 3.2.0.CR1



/**
 * Relation generated by hbm2java
 */
public class Relation  implements java.io.Serializable {


     private RelationId id;
     private Boolean isNative;
     private String entityDescription;

    public Relation() {
    }

	
    public Relation(RelationId id) {
        this.id = id;
    }
    public Relation(RelationId id, Boolean isNative, String entityDescription) {
       this.id = id;
       this.isNative = isNative;
       this.entityDescription = entityDescription;
    }
   
    public RelationId getId() {
        return this.id;
    }
    
    public void setId(RelationId id) {
        this.id = id;
    }
    public Boolean getIsNative() {
        return this.isNative;
    }
    
    public void setIsNative(Boolean isNative) {
        this.isNative = isNative;
    }
    public String getEntityDescription() {
        return this.entityDescription;
    }
    
    public void setEntityDescription(String entityDescription) {
        this.entityDescription = entityDescription;
    }




}


